cli/reporter/print_compact.go

^^ vs the previous version where it was added after the title

🌈 prefix score indication on cli reports

---

README.md
docs/development.md

Move everything to the dev doc and link to that.

📄 Update development docs to match cnquery

---

apps/cnspec/cmd/scan.go
cli/reporter/json.go
cli/reporter/reporter.go
go.mod
go.sum
policy/report.go

Introduces a custom printer to create reports. It doesn't just take the raw data and dump it all to CLI, but instead carefully constructs a JSON representation of the report that is useful for further processing. It contains MRNs for queries, eliminates pesky lookups, and nicely aggregates data.
after: #88 

⭐ scan report --json

---

cli/components/barchart.go
cli/reporter/print_report.go
cli/reporter/render_advisory_policy.go
cli/reporter/render_asset_overview.go
cli/reporter/render_meta_policy.go
cli/reporter/render_policy.go
cli/reporter/reporter.go
go.mod
go.sum
policy/resolved_policy.go

Note: After the migration we are loosing some context from policy bundles, so we don't always have the asset policy available in the bundle. There is a new shared call in the resolved policy, which can help find the top policies given any bundle. This also means that we can hand it any random bundle we are about and given a resolved policy find the root policies that were pulled from the bundle. It helps render policies in order i.e. embedded policies are can be tackled further down. We only need this approach when looking at policies in their hierarchy, as for everything else we can just take the bundle and the results. Since the report displays policies in their hierarchy, it required these new calls.

⭐ restore scan -o report

---

policy/scan/local_scanner.go

fixes issue reported by @arlimus where `cnspec scan local -f policy/examples/example.mql.yaml` has failed when upstream was defined.

🐛  do not use upstream when incognito is active

---

apps/cnspec/cmd/root.go

fix #90 
```
cnspec
___ _ __  ___ _ __   ___  ___ 
/ __| '_ \/ __| '_ \ / _ \/ __|
| (__| | | \__ \ |_) |  __/ (__ 
\___|_| |_|___/ .__/ \___|\___|
mondoo™     |_|              
cnspec is a cloud-native security testing tool for your entire fleet
```

⭐️ new ascii logo

---

apps/cnspec/cmd/scan.go
apps/cnspec/cmd/shell.go

Fix a few things at the source.

Fix typos throwing off spellcheck in docs

---

apps/cnspec/cmd/bundle.go

fixes #109 
```
cnspec bundle fmt example-policy.mql.yaml policy/examples/example.mql.yaml
→ format policy bundle(s) file=example-policy.mql.yaml
→ format file filename=example-policy.mql.yaml
→ format policy bundle(s) file=policy/examples/example.mql.yaml
→ format file filename=policy/examples/example.mql.yaml
→ completed formatting policy bundle(s)
```
I'd also like to mention that you can also pass-in a directory. `cnspec bundle fmt` will recursively walk the directory and format all `.mql.yaml` files.

⭐️ support formatting multiple policy bundle files

---

apps/cnspec/cmd/status.go

```
$ cnspec status                                                                                                                                                                                           
→ Platform:	macos
→ Version:	12.6
→ Hostname:	superhost
→ IP:		192.168.178.20
→ Time:		2022-10-18T23:36:34+02:00
→ Version:	unstable (API Version: unstable)
→ API ConnectionConfig:	https://us.api.mondoo.com
→ API Status:	SERVING
→ API Time:	2022-10-18T21:36:34Z
→ API Version:	6
! API versions do not match, please update the client
→ Owner:	//captain.api.mondoo.app/spaces/mondoo-workstations
→ Client:	no managed client
→ client is registered
→ client authenticated successfully
```

⭐️ new cnspec status sub-command analog to cnquery

---

.goreleaser.yml

Before we have not properly set the build flags for cnquery

🐛 set cnquery version when we build cnspec

---

cli/reporter/print_compact.go

Signed-off-by: Preslav <preslav@mondoo.com>
Fixes showing a passed query as failed:

🐛 Fix query scofing.

---

apps/cnspec/cmd/login.go
apps/cnspec/cmd/logout.go

Brings the login experience to `cnspec`
```
cnspec login --token $MONDOO_TOKEN
→ token will expire at Fri, 21 Oct 2022 15:00:16 CEST
→ config file does not exist, create a new one path=cnspec.yml
→ client //agents.api.mondoo.app/spaces/test-infallible-taussig-796596/agents/2G89H49tT6yJyR37vaGRONzFWuP has logged in successfully
spacerocket.fritz.box:..cnspec ±> cnspec status
→ Platform:	macos
→ Version:	12.6
→ Hostname:	spacerocket.fritz.box
→ IP:		192.168.178.20
→ Time:		2022-10-21T14:52:57+02:00
→ Version:	unstable (API Version: unstable)
→ API ConnectionConfig:	http://127.0.0.1:8989
→ API Status:	SERVING
→ API Time:	2022-10-21T14:52:57+02:00
→ API Version:	unstable
→ Owner:	//captain.api.mondoo.app/spaces/test-infallible-taussig-796596
→ Client: …
```

⭐️ new login and logout subcommands

---

policy/scan/local_scanner.go
policy/scan/scan.go

This allows the upstream communication and reporting of results as well as the use of the Mondoo Vulnerability Database. `cnspec` supports running the Vulnerability Policy and the Platform End-of-Life Policy.

⭐️ use upstream configuration if credentials are provided

---

.vscode/launch.json
go.mod
go.sum
internal/datalakes/inmemory/policyresolver.go
policy/executor/internal/nodes.go

We now check for a specific error type, to check whether a k8s resource vanished.

🐛 Show vanished resources as unscored

---

Makefile
apps/cnspec/cmd/scan.go

The --score-threshold param wasn't being used to determine whether or not the cnspec binary should have a non-zero exit based on the provided --score-threshold parameter.
Walk through the scan results to calculate the worst score and use that to determine whether or not cnspec should exit non-zero.
Signed-off-by: Joel Diaz <joel@mondoo.com>

🐛 use score-threshold param after scan

---

.goreleaser.yml

Release major version containers for each release. Followed [this guide](https://goreleaser.com/customization/docker/#keeping-docker-images-updated-for-current-major)

⭐️ Release major version containers

---

.goreleaser.yml
Dockerfile

Note that this also makes sure it is no longer required to manually update the `Dockerfile` for every release. Now the version is set via a build arg that is set by goreleaser
Fixes #176

⭐️ Release rootless containers

---

policy/scan/local_scanner.go

use the upstream config always, that's what we base our logic on so the params should be coming from there too
Signed-off-by: Preslav <preslav@mondoo.com>

🧹 Make consistent use of UpstreamConfig when initiating connections upstream

---

policy/scan/local_scanner.go
policy/scan/reporter.go

Discussed with @preslavgerchev and @jaym and we agreed that we should add a temporary fix for this problem until we have a more long term solution. Please see if you can come up with any other type of asset that might have the same issue so I can add it to the function that fixes the platform information

🐛 Set container image platform before calling SynchronizeAssets

---

apps/cnspec/cmd/scan.go
policy/report.go

- allow other components to easily reuse the worst score calculation
- is going to be used in https://github.com/mondoohq/packer-plugin-mondoo/pull/48 once merged

🧹 move the worst score calculation to the ReportCollection

---

apps/cnspec/cmd/run.go

aligns descriptions with the feedback from @misterpantz in https://github.com/mondoohq/cnquery/pull/497

🧹 fix cmd descriptions for run command

---

apps/cnspec/cmd/scan.go
apps/cnspec/cmd/serve_api.go
go.mod
go.sum
policy/scan/local_scanner.go

Allow the scanner to use credentials from an inventory job. Only works if that's enabled via `EnableJobCredentials`

Allow using upstream creds from scan job

---

policy/scan/local_scanner.go

If an error is encountered during `SynchronizeAssets` currently cnspec panics. This PR fixes the issue

🐛 Exit if sync assets fails

---

apps/cnspec/cmd/scan.go
cli/reporter/print_compact.go
policy/bundle.go
policy/scan/aggregate_reporter.go
policy/scan/local_scanner.go

fixes #231
- print warning if the `--policy` flag looks like a bundle
- renders asset errors when all assets have an error

🐛 handle case where all assets report an error

---

apps/cnspec/cmd/scan.go

Since we switch to unauthenticated as default, those warning messages are actually not helpful anymore. We display specifically when a service account is used.

🧹 remove unhelpful warning messages

---

apps/cnspec/cmd/bundle.go
apps/cnspec/cmd/login.go
apps/cnspec/cmd/run.go
apps/cnspec/cmd/scan.go
apps/cnspec/cmd/shell.go
apps/cnspec/cmd/status.go
apps/cnspec/cmd/version.go
apps/cnspec/cmd/vuln.go

Suggestions for improving the content used for help and also pulled into the documentation. I'd be grateful for a review to ensure that I haven't changed meaning!
Signed-off-by: misterpantz <letha@mondoo.com>

edits to doc content

---

.github/.goreleaser-edge.yml
.github/workflows/goreleaser-edge.yml

Builds edge containers for every commit to `main`. Will use the latest edge release for cnquery as a base image

⭐️ Add container edge releases workflow

---

internal/plugin/plugin.go

Was getting wierd behavior and it was all because an old build of cnquery was being run instead of what was installed into /usr/local/bin.
Show the path when log level is debug
Signed-off-by: Joel Diaz <joel@mondoo.com>

🧹 show where cnquery will be run from

---

cli/reporter/print.go

This prevents them from showing up in a random order when running help / building documentation

🧹 Sort options for --output

---

internal/bundle/lint.go

This change detects missing asset filter:
```yaml
policies:
- uid: mondoo-azure-security
name: Microsoft Azure Security by Mondoo
version: 1.0.0
specs:
- scoring_queries:
mondoo-azure-security-ensure-os-disk-are-encrypted: null
mondoo-azure-security-ssh-access-restricted-from-internet: null
```
would create an error since the `spec` has no filter defined. The correct one would be:
```yaml
policies:
- uid: mondoo-azure-security
name: Microsoft Azure Security by Mondoo
version: 1.0.0
specs:
- asset_filter:
query: |
platform.name == "azure"
platform.kind == "api"
scoring_queries:
mondoo-azure-security-ensure-os-disk-are-encrypted: null
mondoo-azure-security-ssh-access-restricted-from-internet: null
```

⭐️ detect missing asset filter in policies

---

internal/bundle/lint.go

Before this implementation the linter was displaying an error when there was a policy with pure data queries. This change fixes the warning.

🧹 do not show lint error if the policy spec has either scoring queries or data queries attached

---

apps/cnspec/cmd/login.go

running 'cnspec login' on a fresh system results in a panic
~  % cnspec login
→ no Mondoo configuration file provided. using defaults ! could not initialize certificate authentication error="agent credentials must be set"
panic: runtime error: invalid memory address or nil pointer dereference
avoid adding a nil client plugin so we get a more sensible error:
% ./cnspec login
→ no Mondoo configuration file provided. using defaults ! could not initialize certificate authentication error="agent credentials must be set" FTL failed to log in client error="failed to do request: Post \"https:///AgentManager/RegisterAgent\": http: no Host in request URL"
Signed-off-by: Joel Diaz <joel@mondoo.com>

🐛 avoid panic when no login/token available

---

.goreleaser.yml
apps/cnspec/cmd/backgroundjob/background.go
apps/cnspec/cmd/backgroundjob/healthping.go
apps/cnspec/cmd/backgroundjob/serve_unix.go
apps/cnspec/cmd/backgroundjob/serve_windows.go
apps/cnspec/cmd/scan.go
apps/cnspec/cmd/serve.go
go.mod
go.sum
scripts/pkg/config/mondoo.yml
scripts/pkg/debian/cnspec.conf
scripts/pkg/debian/cnspec.service
scripts/pkg/debian/postinstall.sh
scripts/pkg/debian/preinstall.sh
scripts/pkg/debian/preremove.sh
scripts/pkg/linux/cnspec.conf
scripts/pkg/linux/cnspec.service
scripts/pkg/linux/postinstall.sh
scripts/pkg/linux/preinstall.sh
scripts/pkg/linux/preremove.sh

This change depends on https://github.com/mondoohq/cnquery/pull/786 and https://github.com/mondoohq/cnquery/pull/787
**Problem**
As a user, I want to run cnspec continuously and report the results into Mondoo Platform.
**Solution**
With this new change, `cnspec` has a new `serve` subcommand that runs scans in the background. The package also comes with Linux service configuration for SysV and Systemd.
```bash
cnspec serve
→ loaded configuration from /Users/chris/.config/mondoo/mondoo.yml using source default
→ start cnspec client=//agents.api.mondoo.app/spaces/saha-saha-123/agents/1zDY7auR20SgrFfiGUT5qZWx6mE service_account=//agents.api.mondoo.app/spaces/saha-saha-123/serviceaccounts/1zDY7cJ7bA84JxxNBWDxBdui2xE space=//captain.api.mondoo.app/spaces/saha-saha-123 version=v7.12.1
→ using …
```

⭐️ serve mode for cnspec

---

apps/cnspec/cmd/migrate.go

This fixes error messages during deb/rpm package install

🧹 Add noop migrate command

---

apps/cnspec/cmd/serve.go

This change fixes an issue where an inventory file in the same location as the config is not picked up automatically. This change also allows users to pass in an inventory via the cli flags.

🐛 fix case where the inventory was not auto-loaded in serve-mode

---

policy/scan/local_scanner.go

`serve` mode and the cnspec-runner do not want to show a progress bar.
This fix hides the progress bar, when they explicitly disable it.

🐛 Hide progress bar when explicitly disabled

---

go.mod
go.sum
policy/bundle_test.go
policy/policy.go
policy/policy_test.go
policy/resolver.go

... using the updated cnquery methods to merge base queries and correctly re-generate their checksums.
The current approach had errors when it comes to base and embedded queries. That is because previously we would only deal with what we now call base queries and didn't have to worry too much about any overrides that were happening, because those were limited to scoring specs. However, the latter have now been replaced and merging queries has become the norm. In this world, we need correct checksums for all merged actions.
Additionally, we don't want to alter the structure of query overrides too much, i.e. we don't want to just pull the base query into the override and overwrite the policy group, since that would lose all context of a dependency existing. We will revisit some of this …

🐛 re-activate and fix checksum generation on bundles

---

policy/score_calculator.go
policy/score_calculator_test.go

- if we have nothing, it's unscored
- if we have only skipped stuff, it's unscored
- if we have only skipped and erroneous stuff, it's error
- if we have any results in there, it's a result
adds back the scoring calculator tests
Please also note: Since v8 introduced `Impact` which replaces `Severity`, we internally have to set `Weight` to -1. A weight of 0 just means it won't impact the score, which - unless it is done intentionally - is not the default value. The value of -1 has been chosen to explicitly say that the weight has not been set.

🐛 fix scoring behavior for erroneous assets

---

internal/datalakes/inmemory/policyhub.go
policy/datalake.go
policy/hub.go

It is a remnant of old code and not needed in this context (nor used).

🧹 remove internal reference to query isScored

---

policy/hub.go
policy/resolver.go

After #330 
After the recent change on merging queries (where we now don't overwrite the object anymore) we have been missing the fully realized queries during the resolver step. Restore this by providing both the base queries (in the bundle) and the policy queries.
Fixes the basic query execution that failed after that changed merged in cnquery. Also has the nice side-effect that queries aren't (tried to be) created multiple times if they are referenced by multiple policies in a bundle.

🐛 base query creation and lookup

---

.github/workflows/goreleaser-edge.yml
.github/workflows/goreleaser.yml
Makefile

This fixes:
DEPRECATED: --rm-dist was deprecated in favor of --clean, check https://goreleaser.com/deprecations\#-rm-dist for more details

🧹 Replace deprecated goreleaser arg

---

policy/resolver.go

this is a problem that was introduced with the changes for policy v2. The unset value for weight is -1, not 0.

🐛 fix asset score aggregation

---

policy/deprecated_v7.go
policy/executor/internal/builder.go
policy/executor/internal/nodes.go
policy/resolver.go
policy/score_calculator.go

- the aggregation of impact values has caused e.g. the asset score to become an A, instead of what it actually should be. This is because the default Impact.Value was set to 0, which translates into an INFO score. To remedy this issue, we set the default impact.value to -1 as it should be (and as it is for parsing e.g. bundles)
- additionally, we were missing values for the scoringspec in reportingjobs, which is still in use for v7 clients and will be throughout v8. Make sure we continue to support them

🐛+🧹 fix impact aggregation + scoringspec support

---

cli/reporter/summary.go

When running cnspec with `-o report`, the asset overview looked like this:
```
Summary
=======
Asset Overview
■  A   
■  A   
■  A   
■  X   
■  A   
■  A   
■  A   
■  A   
■  A   
■  A   
■  A   
■  A   
■  A   
■  A   
■  A   
■  A   
```
Now it looks like this:
```
Summary
=======
Asset Overview
■  A   kube-system/kube-scheduler-kind-control-plane
■  A   local-path-storage/local-path-provisioner-684f458cdd-6zl25
■  A   kube-system/coredns-565d847f94
■  X   K8s Cluster kind-kind
■  A   local-path-storage/local-path-provisioner
■  A   kube-system/kube-apiserver-kind-control-plane
■  A   kube-system/coredns
■  A   local-path-storage/local-path-provisioner-684f458cdd
■  A   kube-system/etcd-kind-control-plane
■  A   kube-system/kube-controller-manager-kind-control-plane
■  A …
```

🐛 Display asset names in overview

---

cli/reporter/print_compact.go

Before:
```
→ resolved assets resolved-assets=1
brave_joliot ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────    X score: X
Scanned 1 assets
scratch
X brave_joliot
```
With this fix:
```
→ resolved assets resolved-assets=1
brave_joliot ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────    X score: X
Asset: brave_joliot
-------------------
error: rpc error: code = Unknown desc = cannot find any policy for this search
Scanned 1 assets
scratch
X …
```

🐛 Show errors for asset scans

---

cli/reporter/print_report.go

When we only scanned assets which errored, cnspec would panic:
```
→ resolved assets resolved-assets=1
brave_joliot ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────    X score: X
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x74b2ece]
goroutine 1 [running]:
go.mondoo.com/cnspec/policy.(*Bundle).ToMap(0x0)
/home/christian/workspace/mondoo/github.com/cnspec/policy/bundle.go:224 +0x2e
```
Now, the output looks like this:
```
→ resolved assets resolved-assets=1
brave_joliot ─────────────────────────────────────────────────────────────── …
```

🐛 Don't panic when we only have errors

---

scripts/pkg/debian/postinstall.sh
scripts/pkg/linux/postinstall.sh

if a running mondoo service is detected, the cnspec service is used as a replacement

🧹 post-install script of package migrates mondoo service

---

examples/example.mql.yaml

We were incorrectly using the query field, which is deprecated after v7

🐛 fix policy example for v2

---

policy/hub.go
policy/resolver.go

1: I noticed that with the deprecated policy example data queries
weren't pulled from the bundle. It turns out the code was treating
checks and queries differently. Fixed that.
Additionally, the bundle didn't cache the base objects. Bundles have
a global space to expose shared queries. This is used for both
embed-only queries as well as queries that are actually shared.
However, the code was pushing import objects (i.e. a query that only
has the MRN and nothing else) into the shared query space, instead of
the actual query.
2: Checksums weren't recalculated when base queries were pulled in.
Again, in most v8 cases this wasn't noticeable, but with v7 code this
broke the policy execution.
This PR introduces both a fix to checksums when queries are merged
(just refresh it) as well as a …

🐛 fix incorrect bundle caching and checksums

---

policy/datalake.go
policy/hub.go
policy/resolver.go

After #358
We can largely take the pattern that was established in cnquery now and remove outdated property patterns. Just SetProps for an entity and every other type of property is embedded in either a query, pack, or policy.

🧹 remove unnecessary properties fields

---

policy/deprecated_v7.go
policy/hub.go

- using checkIDs during the queryIDs loop leads to incorrect results at best and panics at worst
- swallowing the error for checksums hides problems

🐛 incorrect query IDs usage + swallowed error

---

policy/bundle_map.go

This is lost in translation, where it correctly errors when we try to modify a query that doesn't exist, but it incorrectly errors if the query exists in the bundle and users try to activate it. Typically we don't run into this case, but the edge-case are policies that were written in v7 and have an explicit action ACTIVATE set.

🐛 don't throw errors if queries in bundles activate

---

.github/.goreleaser-edge.yml
.goreleaser.yml

I copied some things that were not supposed to be in this repo and the release didn't work because of that

🐛 fix copying errors in goreleaser for UBI containers

---

policy/scan/local_scanner.go

This checks whether we have duplicate platformID across the assets.
When not checked here, we would see this:
FTL failed to run scan error='could not create progress bar: number of elements and orderedKeys must be equal'

🧹 Catch asset problems before they reach the progressbar

---

cli/reporter/print_compact.go
policy/scan/local_scanner.go

Before, the progress bars looked like this, when unscored assets where included:
```
kube-system/coredns                                ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────   0% score: U
mondoo-operator/mondoo-client-scan-api             ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────   0% score: U
mondoo-operator/mondoo-operator-controller-manager ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── …
```

🐛 Fix progress for unscored assets

---

.goreleaser.yml
scripts/pkg/windows/windows-upx.sh

This takes the size from 200MB to 50MB. It doesn't work for arm.
Some downsides may be that the binaries now take longer to start. Its also possible that this is more likely to trigger antivirus software.

🧹Compress windows amd64 binary with upx

---

apps/cnspec/cmd/bundle.go
policy/bundle.go

Extract all docs from a bundle. Additional parameters are:
- `--no-ids`: prevents printing of UIDs and MRNs
- `--no-code`: removes all code blocks in docs, treating it as markdown escaped sequences

⭐ cnspec bundle docs

---

cli/reporter/json.go
examples/complex.mql.yaml
policy/bundle.go
policy/bundle_map.go
policy/bundle_test.go
policy/hub.go
policy/policy.go
policy/resolver.go

Allows for variants in checks and queries to be properly executed in v8 (as planned).
The complex policy has been expanded with examples of variants in both checks and queries. We ... could reduce one of those, it's getting full in there, but it does get the point across. See `examples/complex.mql.yaml`
You'll get this output on a Linux system with the above policy:
As you can see: only one of the queries survived and returned the `uname -a` output, while the windows query variant was not run. We don't get more info on the default CLI output and frankly it's great to not confuse it.
Additionally only "A check only run on Linux/macOS" is executed, while the windows variant of the check is not run. We decided to keep the check's metadata, but should probably aggregate it better in a …

🐛⭐ fix variants execution

---

policy/report.go
policy/report_test.go

There's already a function to add, based on the `Score` struct. This PR adds a `Remove` function and adds functions to do the same, this time based solely on `ScoreRating`.

Add functions to remove add and remove ratings from score dist

---

apps/cnspec/cmd/backgroundjob/healthping.go
apps/cnspec/cmd/bundle.go
apps/cnspec/cmd/login.go
apps/cnspec/cmd/logout.go
apps/cnspec/cmd/root.go
apps/cnspec/cmd/scan.go
apps/cnspec/cmd/serve.go
apps/cnspec/cmd/serve_api.go
apps/cnspec/cmd/status.go
go.mod
go.sum
policy/hub.go
policy/scan/local_scanner.go
policy/services.go

Allow cnspec to be told to use a specific proxy for connections to the Mondoo API. In high-to-low order of precedence:
1) MONDOO_API_PROXY env var
2) --api-proxy CLI param
3) api_proxy value in config file
Update the various places in cnspec where connections are set up for the Mondoo API to use the httpclient with proxy.

⭐ allow specifying a proxy just for Mondoo API connections

---

apps/cnspec/cmd/root.go

this way, when the 'login' subcommand goes to save the config file, the --api-proxy that was set via CLI param just goes along for the ride and ends up in the config file.
presently it ends up in the config file as 'api-proxy' which wouldn't be picked up when reading the config file.

🐛 change viper binding from api-proxy to api_proxy

---

apps/cnspec/cmd/scan.go

depends on https://github.com/mondoohq/cnquery/pull/1116 to work properly
related to the discussion in https://github.com/orgs/mondoohq/discussions/855
A simple:
```
docker save debian:11 > debian11.tar  
cnspec scan container tar debian11.tar
```
will then allow you to scan the container image:

⭐️ tar scanning for cnspec

---

cli/reporter/print_compact.go
policy/executor/internal/nodes.go
policy/score_calculator.go

The score for inventory packs is now unscored and no longer error.
Fixes: #482

🐛 Fix the scoring when scaning with inventory packs

---

policy/scan/local_scanner.go

If the scanner is expecting job creds instead of pre-provided upstream creds, init the http client to default to avoid crashes

🐛 Fix empty http client if the scanner does not have upstream config.

---

policy/policy.go

There is a path that throws away data instead of merging queries. It's not clear why it was like that, however when changing a check from ignored to disabled wasn't invalidating the policy

🐛 Fix the checks and queries checksumming for policies

---

policy/hub.go

Seems like a bug. It causes weird behaviour when errors happen since they are ignored

🐛 return err if it's not nil in SetBundleMap

---

policy/hub.go
policy/hub_test.go
policy/scan/local_scanner.go
policy/scan/local_scanner_test.go

his change adds support to filter the policies available in https://mondoo.com/registry by short mrns:
```
cnspec scan okta --organization dev-12345.okta.com --token $OKTA_TOKEN --policy mondoohq/mondoo-okta-security
```

⭐️ allow filtering of policies by short mrns

---

.goreleaser.yml

This PR is not tested yet. Once merged we need to validate the tested edge package.
Reference from nfpm https://nfpm.goreleaser.com/configuration/:
```yaml
overrides:
deb:
depends:
- baz (>= 1.2.3-0)
- some-lib-dev
rpm:
depends:
- baz >= 1.2.3-0
- some-lib-devel
apk:
archlinux:
depends:
- baz
- some-lib
```

⭐️ add cnquery dependency to cnspec package

---

policy/bundle.go
policy/policy_test.go

Without this, we run into stack overflows if we are given a policy with queries that have cycles
After #506

🐛 Check for cycles in variants

---

.goreleaser.yml

turns out #509 was not working properly and docs between nfpm and goreleaser are inconsistent

🐛 fix goreleaser dependency definition

---

policy/scan/local_scanner.go

Fixes nil panics if trying to fetch a vuln report when using incognito.
The vuln report requires upstream communication and it does that via the http client in the UpstreamConfig

pass in default ranger client if using incognito.

---

apps/cnspec/cmd/scan.go
cli/components/question.go

Changes the prompt text to '[Y/n]' and quits upon the first response. Anything. different than 'y' or a 'yes' will *not* upload the report

🧹 Exit browser report prompt if user specifies anything other than a 'y' or a 'yes'

---

apps/cnspec/cmd/status.go

fixes #365
```
→ loaded configuration from /Users/ivanmilchev/Downloads/temp.json using source --config
→ Platform:     macos
→ Version:      13.3.1
→ Hostname:     Ivan-Milchev.local
→ IP:           192.168.2.4
→ Time:         2023-04-24T12:49:43+02:00
→ Version:      unstable (API Version: unstable)
→ API ConnectionConfig: https://us.api.mondoo.com
→ API Status:   SERVING
→ API Time:     2023-04-24T10:49:43Z
→ API Version:  8
! API versions do not match, please update the client
→ Owner:        //captain.api.mondoo.app/spaces/keen-banzai-154123
→ Client:       no managed client
→ Service Account:      //agents.api.mondoo.app/spaces/keen-banzai-154123/serviceaccounts/2OrwvXItmEV0Aue93mep5oPIiS4
→ client is registered
x The Mondoo Platform credentials provided at …
```

🧹 make status err reporting clearer

---

apps/cnspec/cmd/config/config.go
apps/cnspec/cmd/scan.go

Users can now simply share a report via:
```
cnspec scan --share-report
```
If that is not set then the user is asked:
```
Do you want to view or share this report results via Mondoo's reporting service in a browser? [Y/n]
```
To disable the the sharing and not being asked, users either
- use the `--share-report=false` flag
- set the config with the following settings
```
share_report: false # only applicable if used unauthenticated 
```
When a user runs `cnspec scan --share-report` and has disabled the reporting in the config, the cli flag has precedence and therefore the report will be shared.

⭐️ configurable report sharing

---

internal/bundle/lint.go
internal/bundle/lint_test.go

fixes #526
With the new v8 and variants we support queries to have their own asset filter. Therefore policy groups do not necessarily need an asset filter anymore. We still need to see how this shapes out long term but it definitely makes sense not to show the warning when variants are uses since they need to have an asset filter.

🧹 improve linter for variants

---

.vscode/launch.json
apps/cnspec/cmd/scan.go
apps/cnspec/cmd/vuln.go
cli/components/advisories/report.go
cli/reporter/csv_vuln.go
cli/reporter/csv_vuln_test.go
cli/reporter/json_vuln.go
cli/reporter/json_vuln_test.go
cli/reporter/print_vuln.go
cli/reporter/render_advisory_policy.go
cli/reporter/reporter.go
cli/reporter/reporter_test.go
cli/reporter/testdata/mondoo-debug-vulnReport.json

This adds the following output formatters to `cnspec vuln`:
- summary
- full
- json
- yaml
- csv
`cnspec vuln` does not support `junit` and `report`. It will return an error message instead.
Fixes #366

✨ Add different output formatters to `cnspec vuln`

---

apps/cnspec/cmd/serve_api.go

The default HTTP timeout is 30s but sometimes that's not enough. For example, if the mondoo-operator needs to clean thousands of assets, it might take more than 30s. The operator itself sets the timeout for its client to 50minutes or so but the scan API terminates the request on 30s.
Added a flag to allow extending this timeout when needed

🧹 allow specifying custom http timeout for serve-api cmd

---

policy/executor/graph.go
policy/executor/internal/builder.go
policy/executor/internal/graph.go
policy/executor/internal/nodes.go
policy/executor/internal/nodes_test.go
policy/score_calculator.go

This changes the way checks get scored when they're errored. Instead of ignoring them as part of the policy score, they will be scored no different than if they were failing.
This is behind a feature flag "ErrorsAsFailures".
Example policy `errors.yaml`:
```
policies:
- uid: test-pol
name: Errors as Failures Test
specs:
- asset_filter:
query: platform.family.contains(_ == 'unix')
scoring_queries:
my-test1:
my-test2:
queries:
- uid: my-test1
title: erroring check with sev 50
severity: 50
query: |
file("/doesnotexit").content != ""
- uid: my-test2
title: /etc exists
severity: 100
query: |
file("/etc").exists == true
```
```
❯ MONDOO_FEATURES="ErrorsAsFailures" go run apps/cnspec/cnspec.go scan local -f errors.yaml
```
```
Asset: mars
-----------
Checks:
! Error: erroring check with sev 50
✓ …
```

⭐️ Score errors as failures

---

policy/bundle.go
policy/bundle_test.go

Allow variant queries to pull common fields from their parents, if they have not been specified. For example: title, descriptions, and properties.

✨ variants inherit missing fields from parents

---

apps/cnspec/cmd/config/config.go

Detecting CI/CD environments has been broken since the release of v8.8.0 The root cause is that this flag has been renamed here https://github.com/mondoohq/cnspec/pull/543/files#diff-ed60d4b046d856a7d97de76331f9a47e1556bd4443a2efeda3558eb90390080fR26
```
KUBERNETES_ADMISSION_CONTROLLER=1 ./cnspec scan container image redis 
→ loaded configuration from /Users/ivanmilchev/.config/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)
```
This fixes PR fixes the problem:
```
KUBERNETES_ADMISSION_CONTROLLER=1 ./cnspec scan container image redis  
→ loaded configuration from /Users/ivanmilchev/.config/mondoo/mondoo.yml using source default
→ detected ci-cd environment <-- THE IMPORTANT BIT
→ …
```

🐛 fix cicd detection

---

policy/bundle.go

Test example:
```
policies:
- uid: greetings
name: Another policy
version: "1.0.0"
groups:
- checks:
- uid: hello-os
variants:
- uid: ubuntu
- uid: rhel
queries:
- uid: ubuntu
title: Hello Ubuntu
mql: platform.name == 'ubuntu'
filters: platform.name == 'ubuntu'
- uid: centos
title: Hello Centos
mql: platform.name == 'centos'
filters: platform.name == 'centos'
```
Previous output:
```
❯ go run apps/cnspec/cnspec.go scan local -f ./variants.mql.yaml
→ loaded configuration from /home/jaym/.config/mondoo/mondoo.yml using source default
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x82e24de]
goroutine 1 [running]: …
```

🐛 Fix bug where cnspec panics on missing variants

---

policy/hub.go

This is causing panics:
```
go.mondoo.com/cnspec/policy.(*LocalServices).ComputeBundle(0xc020fd25a8, {0xd45b998, 0xc01c77c780}, 0xc020b5e780)
/go/pkg/mod/go.mondoo.com/cnspec@v0.0.0-20230516164323-ea5aaaad968d/policy/hub.go:405 +0x8f4
```

🐛 Assign the computed filters if recomputed

---

go.mod
internal/plugin/plugin.go

We have been swallowing all errors for plugin calls, which made them impossible to debug. I ran into this while debugging https://github.com/mondoohq/cnspec/issues/585 and noticed that as a user, I wasn't able to simply run:
```bash
> cnspec run terraform example.tf -c "terraform.blocks{arguments}"
FTL failed to run query error="rpc error: code = Unavailable desc = error reading from server: EOF"
```
That error is no help.
With this change, we are:
1. exposing the full stack trace of the crashing plugin and
2. formatting a few well-known errors in a way that is more meaningful
Given the above example, I now get:
```
! unknown type *hclsyntax.ParenthesesExpr
panic: interface conversion: interface {} is nil, not string
goroutine 84 [running]: …
```

🐛 report error trace for plugin calls

---

.github/workflows/goreleaser-edge.yml
.github/workflows/goreleaser.yml
.github/workflows/pr-test-lint.yml

just like we did in cnquery, https://github.com/mondoohq/cnquery/pull/1258/files

🧹 set minimum go version to 1.20.4

---

policy/hub.go

I couldn't find where this was getting called and was expecting it be called before attempting to store in the data lake

call prepare framework

---

apps/cnspec/cmd/scan.go
cli/reporter/print_report.go
cli/reporter/reporter.go

The pager wasn't working as expecting and the new defaults with web reporting and compact view do not require us to have that anymore. Lets remove it.

🧹 remove unused flag for report output

---

cli/reporter/print_report.go
cli/reporter/render_asset_overview.go
cli/reporter/render_policy.go
cli/reporter/reporter.go

Fixes issues with the policy report output when `--output report` is used.

🐛 fix report view

---

internal/bundle/lint_results_cli.go

fixes https://github.com/mondoohq/cnspec/issues/615
**before**
```bash
cnspec bundle lint examples/example.mql.yaml
→ lint policy bundle file=examples/example.mql.yaml
RULE ID  LEVEL  FILE  LINE  MESSAGE  
→ valid policy bundle
```
**after**
```bash
cnspec bundle lint examples/example.mql.yaml
→ lint policy bundle file=examples/example.mql.yaml
→ valid policy bundle
```

🧹 improve cnspec bundle lint output

---

apps/cnspec/cmd/backgroundjob/background.go
apps/cnspec/cmd/backgroundjob/serve_unix.go
apps/cnspec/cmd/backgroundjob/serve_windows.go
apps/cnspec/cmd/serve.go

This makes sure that scans get randomly distributed throughout the timer time in an effort to spread out load against the api server.

⭐️ Randomize the start time of scanning in serve mode

---

apps/cnspec/cmd/scan.go
cli/reporter/print_compact.go

This changes the default behavior for sharing reports. Users need to pass the `--share-report` option explicitly.

🧹 make sharing report optional

---

policy/framework.go
policy/resolver.go
policy/resolver_test.go

There are major changes here:
First, compliance frameworks were not connected to the root reporting job. On the backend, we iterate from the root reporting job to figure out all reporting jobs that get saved. Without this, we don't save the compliance frameworks or controls
Second change is the structure of the framework dependencies is preserved in the reporting jobs. For example, asset frameworks point to the space framework which point to the global framework which point to some actual frameworks. This keeps it consistent with the way handle policies.
One issue I ran into was that we have space/asset frameworks and space/asset policies. I chose to not create separate reporting jobs for those because having multiple reporting jobs with the same query is likely to break something. …

Preserve the framework dependencies in the reporting structure

---

Makefile
apps/cnspec/cmd/scan.go
apps/cnspec/cmd/shell.go

This change works in combination with https://github.com/mondoohq/cnquery/pull/1314 and https://github.com/mondoohq/cnquery/pull/1315 to bring GCP compute instance snapshot scanning to cnspec.

⭐️ add help for new gcp instance scanshot

---

policy/bundle_test.go
policy/framework.go

Without this, changing a framework from preview to active produces no change in the framework checksums, and thus we cant store such updates

🐛 Use action when calculating framework graph checksums

---

policy/framework.go

This causes us to load frameworks to calculate checksums we already have. If checksums need to be recalculated, they get cleared first

🧹 Don't unnecessarily recalculate framework dep checksums

---

policy/policy.go

This PR makes sure we are not changing the orders of queries and checks when we update checksums

🧹 do not reorder queries and checks in a policy when updating checksums

---

apps/cnspec/cmd/vuln.go

'cnspec vuln' now shows an error when an unathenticated request is made.
Fixes #629

🐛 show error when unauthenticated

---

internal/bundle/fmt.go

This avoids the case where the formatter sometimes squashes all content into one line

🧹 improve bundle formatter

---

policy/resolver.go
policy/resolver_test.go

For frameworks reporting, we want the ability to display how checks scored for a control. We aggregate the information by check. In some cases, we have checks that have different MRNs but the same code. This makes it difficult to separate these. This change modifies the reporting structure for controls. We don't directly send the check score to the control. Instead, a new reporting job is inserted that reports to the query mrn. And then that reports to the control.

🧹 Report checks by mrn when used by controls

---

policy/resolver.go
policy/resolver_test.go

Frameworks get controls. Controls are pass or fail (0 or 100). By changing the scoring system to average, the value of the framework score is the completion

🧹 Use average scoring for frameworks

---

policy/framework.go
policy/frameworks_test.go
policy/resolver.go
policy/resolver_test.go

🧹 Support controls implemented by controls

---

policy/executor/internal/builder.go
policy/executor/internal/nodes.go
policy/executor/internal/nodes_test.go

Any child of a control that errors is converted into a fail. Any child that is skipped or unscored is converted to pass. This way, controls always have a result

🧹 Change how controls are scored

---

docs/development.md

We used the old release symbol 🎉. Technically not incorrect, but we switched to the different levels of stars and would like to stick to that. Major releases and major capabilities can use 🌟 or even 🌠 (like providers for v9).

📃 update emojiguide

---

.github/workflows/goreleaser.yml

This compliments a similar change to cnquery and includes rc support as well.  Any release tagged with 'beta', 'alpha', or 'rc' in the tag name will skip publishing and only be available from the Github release page for testing purposes.

Support for limited releases of alpha/beta/rc

---

policy/executor/internal/graph.go

Same as https://github.com/mondoohq/cnquery/pull/1742

🧹 Dump resolved policy DOT file if TRACE env var is set.

---

apps/cnspec/cmd/scan.go

Respects the `--inventory-file` flag if that's passed in.

🧹 Respect inventory-file if passed in.

---

examples/example.mql.yaml
policy/executor/graph.go

Currently filter queries that error during the compile stage will cause the execution to fail. However, with the new providers model, certain contents are now optional, thus the local compiler (given locally available schemas) will throw errors. We simply eliminate these filters from the result list.
Example use-case: Have a scanner that only scans github. When it encounters filters, it will get a long list of technologies that are unsupported (like clouds and k8s). These can now simply be eliminated and moved on.

🐛 make filter queries optional

---

apps/cnspec/cmd/scan.go
apps/cnspec/cmd/vuln.go
cli/reporter/print_compact.go

This better matches the more commonly used definition. We will keep fleet working for the next  major version and then slowly deprecate it.
Analogous to: https://github.com/mondoohq/cnquery/pull/1920

✨ rename fleet => inventory

---

apps/cnspec/cmd/root.go

This is in line with cnquery. Additionally, users are missing helpful information if this is set to Warn only, like installation of providers is hidden from them. With this setting active, you get the following output again:
```
> cnspec run gcp project something-1234
→ installing provider gcp version=9.0.1
...
```

🐛 set default logger to info

---

policy/scan/local_scanner.go

Make sync assets go through the `/PolicyResolver` endpoint instead of `/QueryConductor`

🐛 Initialize policy remote services instead of queryhub remote services.

---

.github/workflows/pr-test-lint.yml
cli/reporter/print_compact.go

```
Score Distribution		Asset Distribution
------------------		------------------
A   0 assets      		Azure Subscription   2
B   0 assets
C   0 assets
D   2 assets
F   0 assets
panic: runtime error: index out of range [1] with length 0
goroutine 1 [running]:
go.mondoo.com/cnspec/cli/reporter.(*defaultReporter).printSummary(0x14000969978, {0x140053cdd00, 0x2, 0x140005c1860?})
/Users/vj/go/src/go.mondoo.io/cnspec/cli/reporter/print_compact.go:178 +0xbe0
```

🐛 fix url error in printcompact

---

policy/scan/local_scanner.go

The `GarbageCollectAssets` call was throwing HTTP 403 because the plugins were not set correctly

🐛 fix GarbageCollectAssets authentication for local scanner

---

.vscode/launch.json
policy/scan/local_scanner.go

After https://github.com/mondoohq/cnspec/pull/782
After https://github.com/mondoohq/cnquery/pull/2021
During the resolution, if we only use the (old) asset object, we miss
the part where cnquery fixes the `Backend` field. See: https://github.com/mondoohq/cnquery/pull/2021

🐛 use resolved asset

---

apps/cnspec/cmd/scan.go

🐛 properly handle scans that discover no assets

---

policy/scan/local_scanner.go

this is needed for ci/cd assets

🧹 apply runtime env labels for discovered assets

---

policy/scan/local_scanner.go

do not use ephemeral runtimes for discovered k8s assets. Needed to optimize the memory usage for k8s since we scan hundreds of assets there

✨ re-use provider instance for all assets when scanning k8s

---

apps/cnspec/cmd/root.go

Achieve parity with cnquery:
```
cnspec scan azure --auto-update=false
Error: unknown flag: --auto-update
Usage:
cnspec scan azure [flags]
....
```
vs
```
➜ ~/go/bin/cnspec scan azure --auto-update=false
→ loaded configuration from /Users/preslavgerchev/.config/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)
....
```

🐛 Add the auto-update flag to the root cmd.

---

policy/scan/local_scanner.go

Make sure all providers are killed after scan finishes

🧹 shutdown coordinator after scan

---

apps/cnspec/cmd/policy-example.mql.yaml

this fix the cnspec lint run on the example policy
the lint run of the example policy produce a error
```bash
cnspec bundle lint example-policy.mql.yaml                                                                    x1 16h27m main[bf56f98]
→ lint policy bundle file=example-policy.mql.yaml
RULE ID               LEVEL  FILE                     LINE  MESSAGE
bundle-compile-error  error  example-policy.mql.yaml  1     could not compile
policy bundle:failed
to validate policy:
failed to compile query
'platform.family.contains(_
== 'unix')': cannot find field
'family' in platform
FTL invalid policy bundle
```

🧹 fix asset filter of the example policy

---

apps/cnspec/cmd/scan.go

🐛 Do not exit if annotations not defined in scan/vuln cmd.

---

policy/scan/local_scanner.go

The upstream config is needed to fetch vuln reports.

🐛 Set upstream for ephemeral runtimes

---

policy/hub.go
policy/resolver.go
policy/services.go

Allow us to more easily reconfigure it when needed.

🧹 expose runtime on scanner

---

cli/reporter/junit.go
cli/reporter/print_compact.go
cli/reporter/render_advisory_policy.go
cli/reporter/reporter.go

We recently hotfixed an issue that caused the report not to show on v9+, because older v8 code-paths were taken: https://github.com/mondoohq/cnspec/pull/850
When the upstream reporting eventually switches over to use `asset` instead of `platform`, this hotfix will fail. This PR create a more resilient approach to the vulnerability report, supporting both v8 and v9+

🧹 create a resilient v8 and v9+ vuln report

---

internal/bundle/fmt_test.go

From `platform.` to `asset.`
Not sure if that's the right place.
I want to modify the `example-policy.mql.yml` created when using `cnspec bundle init`

:broom: Set correct filter for `cnspec bundle init` policy

---

cli/reporter/junit.go
cli/reporter/print_compact.go
cli/reporter/render_advisory_policy.go

Many providers do not support vulnerability reports, eg: Anything that requests APIs or files like Terraform/K8s. We support it for things like OSs and OS-related targets.
Example OLD:
```bash
...
✕ Fail:         Verify shielded VM is enabled on compute instances
✓ Pass:         Legacy metadata endpoints enabled
Vulnerabilities:
error: Could not find the vulnerability report.
Scanned 1 asset
Terraform HCL
C Terraform Static Analysis directory pass
```
Example NEW:
```bash
✓ Pass:         VM disk encryption keys should not be provided in plaintext
. Skipped:      Service accounts should not have roles assigned with excessive privileges
Scanned 1 asset
Terraform HCL
C Terraform Static Analysis directory pass
```

🐛 do not print error if vulns are not supported

---

scripts/pkg/linux/cnspec.service

This is in response to https://github.com/mondoohq/installer/issues/279
Adding these conditions will cause the systemd unit to fail is a more elegant way than simply failing because the files aren't present, in the case that the service wasn't registered.  Because we install the unit file with the packages there isn't a direct interface to the user to instruct them to register before instantiating the service.

⭐️ Add conditions to the systemd unit file

---

policy/resolver.go
policy/resolver_test.go

This PRs fixes 2 issues:
1. If we have a framework that references a query but that query is not part of the bundle because the pack or policy are not activated, it will not be present during execution. Add a guard + test to ensure we only add reporting jobs for present queries
2. If there's an active query but it does not match the asset (wrong asset filters), it will not be part of the execution queries. Note it is still part of the bundle, since the pack or policy is active but its not a query that the asset will run. Add a guard + test

🐛 Fix creation of reporting job for missing or non-matching data queries.

---

policy/resolver.go
policy/resolver_test.go

Previously, we used to annotate ignored checks with the `MODIFY` action, we now have a `IGNORE` action too. Clean up of all v7 deprecated code, related to the scoring spec and add a test for a disabled query.
I still need to write a test for a policy with an ignored query

🐛 Fix adding ignored checks in the resolver

---

scripts/pkg/debian/cnspec.service
scripts/pkg/linux/cnspec.service

* RestartLimitBurst defines how many times to retry
* StartLimitIntervalSec > StartLimitBurst*RestartSec
If the number of reboots `RestartLimitBurst` in `RestartLimitIntervalSec` is reached, systemd will stop to restart.
https://github.com/mondoohq/installer/issues/376

🐛 Set maximum retries for systemd

---

policy/scan/local_scanner.go

On distributeJob, we create runtimes but only shut them down at the end of the execution. However, it is possible to exit this function before all runtimes have been executed, i.e. before they all have a chance to shut down properly. With this deferred function we make sure all new runtimes are terminated.
See https://github.com/mondoohq/cnquery/pull/2387

🧹 make sure all asset runtime are shut down after job

---

apps/cnspec/cmd/vuln.go

#911 
Before:
```
./cnspec vuln container image ubuntu:focal-20220113 --log-level debug
DBG using provider os with connector container
DBG Started a new runtime (2 total)
DBG running provider plugin path=/home/marius/.config/mondoo/providers/os/os
DBG Started a new runtime (3 total)
→ no Mondoo configuration file provided, using defaults
FTL failed to parse asset-name error="flag accessed but not defined: asset-name"
```
After:
```
./cnspec vuln container image ubuntu:focal-20220113 --log-level debug
DBG using provider os with connector container
DBG Started a new runtime (2 total)
DBG running provider plugin path=/home/marius/.config/mondoo/providers/os/os
DBG Started a new runtime (3 total)
→ no Mondoo configuration file provided, using defaults
! No credentials provided. Switching to …
```

🐛 fix asset name for vuln command

---

apps/cnspec/cmd/backgroundjob/checkin.go
apps/cnspec/cmd/scan.go
apps/cnspec/cmd/serve.go

Previously, I used the serivceaccount MRN. That does not work on all cases. We need to use the agent MRN.

🐛 Use agent MRN to check in upstream

---

policy/bundle.go
policy/bundle_test.go

We only were checking the `queries` part and not the `checks`, which mean that any policy grp w/o queries would have been skipped. Fixes #925

🐛 Ensure that policy group checks are also properly cleaned if queries are missing

---

policy/bundle.go
policy/bundle_test.go

🐛 Do not add builtin queries if there are none.

---

policy/bundle.go
policy/bundle_test.go

This is more of an internal feature, but a function to let us merge a cnquery (explorer) bundle and a policy bundle together.

✨ Add FromQueryPackBundle, allowing conversion of an explorer bundle to a policy bundle.

---

policy/scan/local_scanner.go

Removing policies from the bundle on filter calls actually caused havoc because it removed potentially dependent policies from the bundle. For example: if you bundle has policy A + B, and B depends on A, and you set `--policy` to `B`, then A gets removed from the bundle and leads to errors.
We only need to remove the policy from the list of executed policies in the resolver, not from the bundle itself.

🐛 filter policies without removing them from the bundle

---

apps/cnspec/cmd/serve.go

Fixes https://github.com/mondoohq/cnquery/issues/2461

🧹 Update providers when running in serve mode

---

policy/scan/local_scanner.go
policy/scan/local_scanner_test.go

In case recording isn't specififed during scanner initialisation, set the NullRecording

🧹 Prevent nil panic when recording is not set

---

cli/reporter/print_compact.go

Controls alone is too generic of a heading.

Be more clear on the CLI that we're showing compliance controls

---

internal/bundle/bundle.yac.go
internal/bundle/bundle_test.go
internal/bundle/fmt.go
internal/yac-it/yac-it.go

Before this change the `cnspec bundle fmt` format removed head comments. Sometimes its nice to be able to attach comments and preserve it. Its quite tricky with the yaml library. We work around this by overwriting the Unmarshal and Marshal function. We do not preserve all comments yet since there is way more fine-tuning required to make this work.
The following is working now:
```yaml
policies:
- uid: sample-policy
name: Sample Policy
version: 1.0.0
```

⭐️ preserve head comments

---

go.mod
go.sum
policy/scan/disk_queue.go
policy/scan/disk_queue_test.go
policy/scan/pdque/queue.go
policy/scan/pdque/queue_test.go

Fixes https://github.com/mondoohq/mondoo-operator/issues/852

⭐️ replace dque with pdque

---

internal/bundle/bundle_ext.yac.go
internal/bundle/fmt.go
internal/bundle/fmt_test.go

The yac bundle holds extra properties (file context, comments). To avoid losing those we add a `SortContents` function to the yac `Bundle` struct

🧹 Add sortContents to yac bundle struct. Simplify formatting.

---

policy/resolver.go
policy/scan/local_scanner_test.go
policy/scan/testdata/shared-query.mql.yaml

Fixes #960
I think this solves the problem we have seen in the issue above. I broke this in #943. There was even a discussion about that specific change https://github.com/mondoohq/cnspec/pull/943/files#r1392963805 The intention there was that we do not override scores if they already exist, since that was breaking the new exceptions logic. 
I think I messed it up because with the flow in that PR there are situation where the score would be completely missing from the reporting job and that causes panics. I re-wrote the code to only set the score if it's not already set. That works for exceptions and also fixes the panic

🐛 fix reporting job score panic

---

policy/resolver.go
policy/scan/local_scanner_test.go

Rejected exceptions shouldn't count as exceptions. That bit was missing from the original implementation, so I added it here

🐛 fix rejected exceptions execution

---

policy/bundle.go
policy/bundle_test.go

- We cannot change a value of the mquery before its stored. This causes the checksum to change. Its better we do this before we calculate checksums. I've made this happen when the bundle is compiled
- The queries variants refer to need to have their checksums before we checksum it. So we need to topologically sort the queries before compiling such that all dependent queries have been compiled and checksummed before compiling the depending query.

🐛 Try to make mquery checksums stable

---

policy/scan/local_scanner.go

This fixes the error:
'unable to detect platform for asset ...'
I came across this with container image discovery.

🐛 Fix missing platform

---

policy/scan/local_scanner.go

Instead of calling `SynchronizeAssets` once for all discovered assets, we create batches. This makes sure that if we have discovered a huge amount of assets, the call would still succeed. 
I intentionally put a low number for the batch size because with this implementation, batches are scanned in parallel, which also decreases the total scan time.
Downside of this approach is that the progress bar results ordering is no longer deterministic. However, since this is a progress bar, I don't think ordering should matter

🧹 batch sync assets

---

policy/framework.go
policy/frameworks_test.go

The review status actually changes the execution for a framework so we need to include it in the execution checksum

🐛 add review status to framework execution checksum

---

policy/resolver.go
policy/resolver_test.go

Until now we had always deleted the data queries' reporting jobs and attached the datapoints to their parent RJs. With this change we instead attach the datapoints to the data queries' RJs and we do not delete them. 
This means that we now have scores coming in for data queries, even though those will always be of the unscored type.
This brings scoring and data queries a lot closer in terms of their behaviour in the resolver. For instance, we no longer need to do special handling for framework controls and data queries, those work just like the checks.
I need to write more tests for this but the code changes should be there

⭐️ Add reporting jobs for data queries.

---

cli/reporter/cli_reporter.go
cli/reporter/file_handler.go

This adds a reporter which allows to access the rendered report as bytes.Buffer. This is needed, so we can output it inside the packer plugin.
For reference: https://github.com/mondoohq/packer-plugin-cnspec/pull/170

🧹 Add bytes reporter to support the packer plugin

---

examples/props.mql.yaml
policy/bundle.go

Note: Please update cnquery to latest post https://github.com/mondoohq/cnquery/pull/2973 and this should work
1. The `for` field is used to specify what a prop is meant to set. Unfortunately it was not used during resolution, so it was effectively ignored so far.
2. Properties have been hard to use because they lack documentation. This PR adds a full example on how properties work and how they can be used across properties.
Given the new example, we can now run:
```bash
cnspec scan -f examples/props.mql.yaml
```
```
Data queries:
home.+: "ex on 1"
home.+: "ex on 2"
homeDir.+: "ex on 3"
```
It also now supports overrides:
```bash
cnspec scan -f examples/props.mql.yaml --props userHome="'nya'"
```
```
Data queries:
home.+: "nya on 1"
home.+: "nya on 2"
homeDir.+: "nya on 3"
```

🐛 fix merging of `for`-referenced props + add example

---

policy/scan/disk_queue.go

The current size is too small. We are scanning clusters with dqueue and 500 entries is just not enough. There are cases where we queue all the objects in the cluster to be scanned sequentially... The actual thing that gets stored on the disk is the inventory file to be scanned, which is not large. I increased the limit significantly

🧹 increase dqueue max size

---

internal/datalakes/inmemory/policyhub.go
policy/hub.go
policy/scan/aggregate_reporter.go
policy/scan/local_scanner.go
policy/scan/reporter.go

After #1023 and some thoughts and discussions on this topic, I tried out something else. It turns out we don't need the bundle at all for execution and reporting results upstream. We only use it to print the CLI report. 
This PR makes sure we aren't pulling the bundle for every asset. It needs a small backend change that will allow agents to call `GetPolicyFilters` but apart from that it works exactly the same as the old code
Another benefit of this approach is that we will use significantly less network traffic. This has become a problem for big k8s cluster that result in many assets being scanned

🏃🏻‍♂️ improve scan speed by not retrieving bundles for assets

---

apps/cnspec/cmd/backgroundjob/background.go
apps/cnspec/cmd/config/config.go
apps/cnspec/cmd/config/config_test.go
apps/cnspec/cmd/serve.go

fixes #653
You can now pass in alternative values to `cnspec serve` to configure the timer and its splay.
```bash
> cnspec serve --help
Start cnspec in background mode.
Usage:
cnspec serve [flags]
Flags:
-h, --help                    help for serve
--inventory-file string   Set the path to the inventory file
--splay int               randomize the timer by up to this many minutes (default 60)
--timer int               scan interval in minutes (default 60)
Global Flags:
--api-proxy string   Set proxy for communications with Mondoo API
--auto-update        Enable automatic provider installation and update (default true)
--config string      Set config file path (default $HOME/.config/mondoo/mondoo.yml)
--log-level string   Set log level: error, warn, info, debug, trace (default "info")
-v, …
```

⭐️ allow customisation of scan interval

---

apps/cnspec/cmd/bundle.go
apps/cnspec/cmd/migrate.go
apps/cnspec/cmd/policy.go
apps/cnspec/cmd/scan.go
apps/cnspec/cmd/serve.go
apps/cnspec/cmd/serve_api.go
apps/cnspec/cmd/shell.go
apps/cnspec/cmd/version.go
apps/cnspec/cmd/vuln.go
go.mod
go.sum
test/cli/testdata/cnspec.ct
test/cli/testdata/cnspec_scan.ct
test/cli/testdata/cnspec_vault.ct

This PR simplifies the short descriptions and does not end with trailing dots

🧹 remove trailing dot for short cmd description

---

examples/compliance.mql.yaml
examples/directory/example1.mql.yaml
examples/directory/example2.mql.yaml
examples/lint_test.go
examples/props.mql.yaml

Use our lint requirements to validate our examples. To make this work, we temporarily install the required providers and remove them afterwards. This ensures that other tests like cli tests are not affected by the providers we need here.

🧹 ensure example pass our own lint requirements

---

.github/workflows/pr-test-lint.yml

This makes sure different runs use different provider install directories. It shields PRs better and makes sure we test properly.

🧹use custom provider directory for pipeline

---

.github/workflows/main-benchmark.yml
.github/workflows/pr-test-lint.yml
Makefile
policy/scan/benchmark/benchmark_test.go
policy/scan/testdata/kubernetes-security.mql.yaml

add benchmark testing that compares every commit in a PR with latest `main`. If the diff is above 150%, it errors out and it comments on the violating commit. Looks like this https://github.com/mondoohq/cnspec/commit/6e83272f1a7de7f8c95eb0f57e7f0767409f695a#comments
we also get a job summary like this https://github.com/mondoohq/cnspec/actions/runs/7643019168#summary-20824279571

✨ add benchmark test for scans

---

internal/bundle/bundle.yac.go
internal/bundle/fmt_test.go
internal/bundle/yacit/main.go

Before variants key was always sorted after the docs. This reads strange. Not variants are rendered before docs similar to mql.

🧹 move variants before docs

---

policy/scan/local_scanner.go
policy/scan/local_scanner_test.go

This implements the same [behavior](https://github.com/mondoohq/cnquery/pull/3152) we added for cnquery to cnspec.
When cnspec was executed in a pipeline and a connect error happened, we never collected that error and returned a non-zero exit code. That can lead to silent errors.
We always prepared the report structure to collect the errors. This change handles asset errors now.
**before**
```shell
> cnspec scan ssh user@host.com
x unable to connect to asset error="rpc error: code = Unknown desc = dial tcp 104.21.31.241:22: connect: operation timed 
> echo $?
0
```
**after**
```shell
> cnspec scan ssh user@host.com
x unable to connect to asset error="rpc error: code = Unknown desc = dial tcp 104.21.31.241:22: connect: operation timed out"
Asset: 
-------
error: rpc error: code = Unknown …
```

🐛 report asset errors

---

.github/workflows/pr-test-lint.yml
policy/policy.go
policy/policy_test.go
policy/resolver_test.go

We need the group type and review status to be part of the policy graph execution checksum since these 2 fields can actually change the execution job (for exceptions)

🐛 add group type and review status to policy graph execution checksum

---

policy/resolver.go
policy/resolver_test.go

In #1036, code was added to prune nodes that were being used. However, this happens before the frameworks get a say in what happens. This meant it was possible to prune the root reporting job casuing the resolved policy to be broken

🐛 Fix resolved policy root pruning bug

---

apps/cnspec/cmd/scan.go
policy/scan/fetcher.go
policy/scan/local_scanner.go
policy/scan/reporter.go
policy/scan/reporter_aggregate.go
policy/scan/reporter_aggregate_test.go
policy/scan/reporter_error.go
policy/scan/reporter_noop.go

fixes https://github.com/mondoohq/cnspec/issues/1071
When we run scans we have 3 different cases we need to handle:
1. use local bundle
2. public registry, which is default when not authenticated with Mondoo platoform and no local bundle was provided
3. authenticated with Mondoo platform with upstream reporting
4. authenticated with Mondoo platform in incognito mode but with upstream policies
Before this PR we did different ways of handling. We harmonize the fetching of the bundles for the reported now. We always use the services.GetBundle() independently of the cases above. This simplifies the code base.
It is also important to note that having a configuration does not mean that it includes upstream config. A simple config could be:
```yaml
auto_update: true
log-level: info
```
TODO:

🐛 fix reporting when policies are fetched from public registry

---

.copywrite.hcl
apps/cnspec/cmd/policy-example.mql.yaml

... otherwise this generates policy files that always have Mondoo copyright and license info in the header. This is a bit of overkill in most use-cases, so we can lighten it.

📃 remove license header from cnspec policy init

---

apps/cnspec/cmd/serve.go
policy/scan/local_scanner.go

this will make sure we aren't calling `GetBundle` when running in `cnspec serve` mode. We don't really need it, since we only care about the errors

🧹 use error reporter when running serve command

---

apps/cnspec/cmd/scan.go

make sure we set the upstream config for the default runtime

🐛 set upstream config for scans

---

.goreleaser.yml
Makefile
apps/cnspec/cmd/shell.go

The problem was that we have not set the cnquery version variables properly. The shell had special handling which I removed to ensure we have consistent results. This has not affected prod builds, just dev builds.
**before**
```
±> cnspec run -c "mondoo.version"
mondoo.version: "unstable"
±> cnspec shell -c "mondoo.version"
→ connected to macOS
___ _ __  ___ _ __   ___  ___ 
/ __| '_ \/ __| '_ \ / _ \/ __|
| (__| | | \__ \ |_) |  __/ (__ 
\___|_| |_|___/ .__/ \___|\___|
mondoo™     |_|              
mondoo.version: "v10.3.4"
```
**after**
```
±> cnspec run -c "mondoo.version"
mondoo.version: "v10.3.4"
±> cnspec shell -c "mondoo.version"
→ connected to macOS
___ _ __  ___ _ __   ___  ___ 
/ __| '_ \/ __| '_ \ / _ \/ __|
| (__| | | \__ \ |_) |  __/ (__ 
\___|_| |_|___/ .__/ \___|\___| …
```

🧹 harmonize the version handling for mondoo.version

---

.github/workflows/bump-cnspec-in-deps.yaml

This trigger a PR creating in the dependant repos:
- packer-plugin-cnspec
These repo will then create a PR to get the submitted cnspec version.

✨ Trigger cnspec bump in dependant repos

---

cli/reporter/azure_service_bus_handler.go
go.mod

* Set a timeout on sending the message to 30s.
* Set the right content type if the report is JSON
* Use a custom cred resolver. The default implementation sets the timeout to a second. I have observed random, inconsistent failures related to that when working with the default creds. Use a custom chain resolver that sets the timeout to 5 seconds instead (this should be more than enough). This resolver also works with CLI. env and workload creds, covering almost all cases

⚙️ Add timeout when sending message to a service bus. Use a custom cred chain to workaround managed identity cred issues.

---

policy/scan/local_scanner.go

When we encounter errors before we have the deferred for closing the progress bar, the logger remains paused. This means the error is not printed. 
Fixes #1034

🐛 show scan errors

---

cli/reporter/print_compact.go

Instead of:
Do:
We may abolish letter-grading in favor of criticality-grading in the future, but either way numeric scores should be visible to see meaningful changes.

✨ show numeric score in cli for assets

---

policy/executor/internal/collector.go

Both `SinkData` and `SinkScore` are calling `StoreResults`. We need to make sure we call `StoreResults` with `IsLastBatch = true` only once for each scan. 
This PR changes the way we send scores and data. We now combine both in a single call. This makes the code easier to understand and reduces the amount of roundtrips we do per scan

🧹 make sure we set IsLastBatch only once

---

policy/scan/local_scanner.go
policy/scan/reporter.go
policy/scan/reporter_aggregate.go
policy/scan/reporter_error.go
policy/scan/reporter_noop.go

When we do not use the `AggregateReporter` we don't care about vulnerabilities at all. This change will make sure we aren't calling `GetVulnCompactReport` when running `cnspec serve` and `cnspec serve-api`

🧹 only pull vuln report for AggregateReporter

---

policy/scan/local_scanner.go

the platform was not updated upstream when delayed discovery was active for an asset

🐛 make sure platform is sent upstream for delayed discovery

---

apps/cnspec/cmd/scan.go
test/cli/testdata/cnspec_scan.ct

Followup on https://github.com/mondoohq/cnspec/issues/1124 since we learned that the flag name was not intuitive.
Depends on https://github.com/mondoohq/cnquery/pull/3570

🧹 use new `inventory-format-ansible` and `inventory-format-domainlist` names for flags

---

policy/scan/local_scanner.go

Do not log the full asset when starting a scan as this may log sensitive data such as credentials, stored in the asset's connnection.

🧹 Do not log full asset.

---

apps/cnspec/cmd/serve.go

make sure we handle auto update config in serve command. If the `MONDOO_AUTO_UPDATE` env var is set to `false`, we should skip provider updates. This is already handled in cnquery but seems to be missing here. We need it to work for the mondoo-operator node scanning

🧹 handle auto update config in serve command

---

apps/cnspec/cmd/serve.go

We are now printing an error message if agent MRN isn't set. That isn't an error because we can run `cnspec serve` without an agent MRN. I changed the level to debug

🧹 do not log error when checkin cannot be initialized

---

examples/risk.mql.yaml
policy/executor/internal/collector.go

The logic on the risk factors examples had been inverted by accident.

🐛 fix inverted risk factor evaluation

---

policy/risk_factor.go
policy/risk_factor_test.go

This keeps the computation separate between the risk score and the base score.
@chris-rock FYI for the vulnerability score. The best way to use this is to set the 
```
score.RiskScore = score.Value
``` 
to get started. The add all risk factors to the score:
```
for i := range risks {
risks[i].AdjustRiskScore(score, isDetected)
}
```
This prevents any changes to the base `Value` of the score, so that we always have access to it.

🧹 AdjustRiskScore to not adjust base score

---

policy/resolver.go

this would routinely drop through the filter on the resolution step. With the support of empty policies with risk factors a dependency chain works as intended again.

🐛 support empty policy with only risk factors

---

policy/risk_factor.go
policy/risk_factor_test.go

We ignored value changes in this field because the float was mapped (and rounded) to an integer before adding it to the checksum. Despite having a test for this case, the test didn't catch this case because other changes to the RiskFactor caused changes in the checksum.
We now have a standalone method for generating data for RiskFactor tests and additional validations that the generation produces unchanged data. (This approach is also more efficient than a deep-clone via proto)

🐛 fix RiskFactor Checksum with Magnitude field

---

apps/cnspec/cmd/backgroundjob/serve_unix.go
apps/cnspec/cmd/backgroundjob/serve_windows.go

Running `cnspec serve` with the following config (relevant bits only included):
```
scan_interval:
timer: 60
```
panics as the splay is 0. This PR adds a safeguard to ensure cnspec doesn't panic if it's only the timer that has been set

🐛 Fix serve panics if splay is zero.

---

apps/cnspec/cmd/backgroundjob/checkin.go
apps/cnspec/cmd/backgroundjob/checkin_pinger.go
apps/cnspec/cmd/serve.go

Whenever running a scan via `cnspec serve`, ensure to also check in the managed client for consistency. To achieve this:
* Split the `checkinpinger` into `checkinhandler` and `checkinpinger`. The first one knows only how to perform a check in upstream. The latter one knows only how to run a timer-based function and to call `checkinhandler`
* Re-use the `checkinhandler` when running the scan

✨ Perform check-in for the client when running a scan via cnspec serve.

---

policy/executor/internal/collector.go
policy/risk_factor.go

We will wait to send scores to the server until all of them have been collected. This helps us to update all the scores with the available risks in the client before sending them.
Follow-up: We may want to batch up the number of scores we send and possibly split out the data from the remaining score upload if there is a lot to send. Ultimately, the last batch (which sets the scan to done) must contain all policies, which makes it easy to consume them in just one request.
We also restructure risks so that the list is only created when we are ready to store them. Once consumed the risk index is emptied out.

🧹 only submit scores once we are done

---

internal/datalakes/inmemory/policyhub.go
internal/datalakes/inmemory/policyresolver.go

When running against upstream policies, we don't get risk factors from the policy bundle, since we generally don't need the bundle to run the scan. However, we do require basic risk factor info to help score everything before we send data up.
In this change we pull risk info from the resolved policy and inject it into the inmemory datastore before the scan is started (unless the risk factor exists for any reason, like prior policy bundles). It has enough information for scoring.
For any later reporting step we may still inject all risk factor metadata into the inmemory store before printing the output.

🐛 fix risk factors missing in inmemory w/ upstream

---

cli/reporter/print_compact.go

✨ print a grayed section if no risks are downgrading the asset

---

policy/executor/internal/collector.go

This will ensure we don't have to separately batch scores (since their data size is limited) while we still get to batch up data as it's coming in.

✨ always separate StoreResults for score + data

---

policy/risk_factor_test.go

Setting the match to negative changes the risk score, which is what we want in the test.
Because we use integers, the score may be off by a rounding error, fyi.

🐛 fix risk scoring test

---

apps/cnspec/cmd/scan.go
cli/reporter/cli_reporter.go
cli/reporter/print_compact.go

Fixes #1228
Aligns the display of the asset MRN with the `StoreResourcesData` feature flag

🐛 Print asset MRN only if StoreResourcesData is enabled.

---

policy/executor/internal/execution_manager.go

It seems like the executor does too many allocations and the GC cannot keep up with cleaning them up. For assets where we execute many queries, the memory can spike a lot for this reason. Now that we force the GC to run, the memory stays low. 
This is a temporary fix and we should come back and make sure we address the underlying issue instead of calling the GC manually
Discussed with @arlimus

🩹 fix executor memory issue

---

policy/executor/internal/execution_manager.go

this is causing a large spike in CPU usage making scans really slow in environments with insufficient CPU. We need to find a better way to fix this issue

🧹 revert GC change in execution manager

---

policy/bundle.go
policy/bundle_test.go
policy/evidence.go
policy/evidence_test.go

This is a follow-up to #1246 
* Generate one policy per framework. Evidences are now pulled into policy groups rather than separate policies.  This means  we do not have to deal with multiple policies, specially for larger frameworks.
* Add `GenerateEvidenceObjects` onto a framework which will pull out the evidence and return both a policy and a framework map.
* Pull out generation code entirely into `evidence.go`. This makes it fully testable, the bundle now only calls `GenerateEvidenceObjects`.
* Improve tests

⭐️ Improve compliance framework evidence generation.

---

policy/cnspec_policy.proto

This is added to the proto as a reference for the currently supported risk factors. Every category of risk factory may have multiple specific implementations.

📃 describe types of indicators for risk factors

---

cli/reporter/print.go

after https://github.com/mondoohq/cnspec/pull/1244
This PR enables the v2 json format as standard. The new format is accessible via:
```
cnspec scan local --json
```
or 
```
cnspec scan local --output json
```
For backwards-compatibility, the old format is available via:
```
cnspec scan local --output json-v1
```

🛑 switch to json v2 output format

---

policy/executor/internal/execution_manager.go

Provide a way to debug the memory usage per executed query. This is intentionally not a debug message, because we need to read extra info to be able to print it. It is also not tied to the existing `DEBUG` flag because that one is storing bundles locally and switching the log output to debug. Storing the bundles would not work in a k8s setup because we have the entire filesystem as read-only.

🔨 provide a way to debug memory usage per query

---

apps/cnspec/cmd/scan.go
apps/cnspec/cmd/vuln.go
cli/reporter/cli_reporter.go
cli/reporter/cli_reporter_test.go
cli/reporter/file_handler.go
cli/reporter/json_test.go
cli/reporter/output_handler.go
cli/reporter/print.go
cli/reporter/print_compact.go
cli/reporter/print_test.go

This introduces a series of new optios for the default CLI output printer. These give far greater control over which sections are printed (or rather not printed).
As a follow-up, we should enabled these for the other output formats as well.
For all options, run:
```
> cnspec scan -o help
Available output formats: compact, csv, full, json, json-v1, json-v2, junit, report, summary, yaml, yaml-v1, yaml-v2.
Available options: [no]checks, [no]controls, [no]data, [no]vulns.
Combine with commas, example: compact,nodata,nocontrols
```
Example usage (from this help):
```bash
> cnspec scan -o compact,nodata,nocontrols
```

🌈 add additional output options

---

cli/reporter/junit.go

The bundle can be empty if cnspec encountered an error during scanning. In that case, we need to make sure we don't exit with a panic

🐛 fix junit reporter panic

---

.copywrite.hcl
.github/actions/spelling/line_forbidden.patterns
.github/actions/spelling/reject.txt
LICENSE
policy/evidence.go
policy/evidence_test.go
policy/executor/internal/execution_manager.go

Update spellcheck config + copyright year

---

cli/reporter/print_compact.go

Before:
```
Scanned 13 assets
Kubernetes CronJob
[45/100]   mondoo/restart-nexus
Kubernetes DaemonSet
[45/100]   amazon-cloudwatch/fluent-bit
[45/100]   kube-system/replace-gvisor-platform-flag
Kubernetes Deployment
[45/100]   argocd-repo-server
[50/100]   kueue-system/kueue-controller-manager
[0/100]   mondoo-enterprise-operator/mondoo-enterprise-operator-controller-manager
[45/100]   mondoo-operator/mondoo-operator-controller-manager
[0/100]   mondoo/mondoo-job-runner-controller-manager
```
After:
```
Scanned 13 assets
Kubernetes CronJob
[45/100]    mondoo/restart-nexus
Kubernetes DaemonSet
[45/100]    amazon-cloudwatch/fluent-bit
[45/100]    kube-system/replace-gvisor-platform-flag
Kubernetes Deployment
[45/100]    argocd-repo-server
[50/100]    kueue-system/kueue-controller-manager …
```

🧹 align asset scores in CLI report

---

.goreleaser.yml

With this change, it can override the existing release files. This can help in case something goes wrong.

🧹 Allow re-running the goreleaser job

---

policy/score_calculator.go
policy/score_calculator_test.go

We ignore all scores that are out of scope, disabled or ignored from the policy score calculation

🐛 fix policy scoring with exceptions

---

policy/executor/internal/collector.go

If a query was used for a risk factor, its score was always being filtered out, regardless of if it might have been used outside of risk factors

🐛 Don't filter out scores of queries used for risk factors and not

---

policy/score_calculator.go
policy/score_calculator_test.go

Second attempt at fixing banded scoring, after #1350 didn't fully work

🐛 attempt to fix banded scoring with exceptions

---

policy/score_calculator.go

Not all calculators handle ignoring score properly. That code is still needed

Revert changes to AddSpecdScore

---

apps/cnspec/cmd/scan.go

Add support to set the output as env variable:
```bash
export MONDOO_OUTPUT=nodata,nocontrols
cnspec scan local  
```

🧹 support MONDOO_OUTPUT as env variable

---

policy/score_calculator.go
policy/score_calculator_test.go

Variations within bands were inverted and led to incorrect results on the edges of those variations i.e. if all scores within a band were failing or only one was failing. The tests reflect have been added to test out this behavior of variation within bands and will be further expanded in the future.

Critical: Fix banded scoring within individual bands

---

policy/resolver.go
policy/resolver_test.go

We have a case where an incorrect data query is being tied to a control by mrn. This happens when there is duplicate code ids for different mrns.
This is causing a resolved policy to be created where the child jobs are not consistent with notifies. When executed, things get scored as a U.

🐛 Don't tie incorrect data to controls

---

.github/workflows/pr-test-lint.yml

Currently the auto-approve job is skipped:
https://github.com/mondoohq/cnspec/actions/runs/10662782067/job/29550833769?pr=1414
The workflow is triggered by a push event and not a pull_request event. I need to figure out how to use the metadata step, with a push event.
All the examples work on a pull_request: https://github.com/dependabot/fetch-metadata

🧹 Debug dependabot auto-approve PRs

---

.github/workflows/pr-test-lint.yml

2nd try
We cannot use the examples from the docs because we trigger this workflow on 'push' and not on ' pull_request'.

🤖 Auto approve go dep PRs by dependabot

---

.github/workflows/pr-test-lint.yml

The command failed here: https://github.com/mondoohq/cnspec/actions/runs/10701181061/job/29666754075?pr=1419
> gh pr review --comment "@dependabot squash and merge" --approve "$PR_URL"
...
accepts at most 1 arg(s), received 2
Error: Process completed with exit code 1.
Giving the docs another try, I think, this might be the correct syntax.

🐛 Fix the gh cli command

---

policy/bundle.go
policy/reportingjob.go
policy/resolver.go
policy/resolver_test.go

Compliance only knows about parent MRNs and not variant MRNs. To allow a mapping from compliance control to executed check, we need to store the check with it's parent MRN.

🐛 Find variant checks by parent MRN

---

cli/reporter/print_compact.go
cli/reporter/render_asset_overview.go
cli/reporter/render_policy.go
go.mod
go.sum

Boolean data queries had an assessment and would print that instead of just the result
Requires https://github.com/mondoohq/cnquery/pull/4693

🐛 Don't render assessments for data queries

---

go.mod
go.sum
policy/executor/internal/collector.go

There is an upper limit to what is accepted by the platform per request. Make sure we do not go past it when sending data.

🐛 Chunk sending results by size

---

go.mod
go.sum
internal/tfgen/hcl.go
internal/tfgen/hcl_internal_test.go
internal/tfgen/hcl_test.go

This is the first step to start writing automation code to onboard integrations into the Mondoo platform.
`tfgen` is a primitive that will help us write HCL code in plain Go programming language. We will use it
to generate automation code from a new command named `cnspec integrate ...`. Terraform code can
be complex, for example, to integrate a Google project into the Mondoo platform, a user would write
this HCL code:
> https://registry.terraform.io/providers/mondoohq/mondoo/latest/docs/resources/integration_gcp
With `tfgen`, we can write that code in Go like:
```go
mondooProvider, err := tfgen.NewProvider("mondoo", tfgen.HclProviderWithAttributes(
map[string]interface{}{
"space": "hungry-poet-123456",
},
)).ToBlock()
googleProvider, err := tfgen.NewProvider("google", …
```

✨ new `tfgen` go package to generate hcl code

---

.github/workflows/goreleaser.yml

This was part of a refactor by Sam that was rolled back, however this hook was left in place.  Removing it will allow the gorelease job to finish green.  We will plan to come back and complete the automation between cnspec and installer in the future.

Remove the release hook which is failing

---

apps/cnspec/cmd/integrate.go
internal/onboarding/azure.go
internal/onboarding/constants.go
internal/onboarding/exec.go
internal/onboarding/exec_test.go

This PR adds three more flags to the experimental command `cnspec integrate azure`.
`--allow`, `--deny` used to control the integration of subscriptions. By default, all subscriptions will be discovered and integrated for continuous scanning.
To choose the subscriptions to scan, pass the list of subscriptions using the `--allow` flag.
cnspec integrate azure --allow <subscription_id_1> --allow <subscription_id_2>
To scan all subscriptions expect those you specify, pass the list of subscriptions you don't
want Mondoo to scan using the `--deny` flag.
cnspec integrate azure --deny "<subscription_id_1>,<subscription_id_2>"
The new `--scan-vms` enables scanning VMs on Azure subscriptions via RunCommand.
**NOTE** that --allow and --deny are mutually exclusive and can't be use together.
Finally, …

⭐️ allow and deny subscriptions + scan VMs options

---

.github/workflows/pr-test-lint.yml

That should fix:
https://github.com/mondoohq/cnspec/actions/runs/11910492758/job/33190215560?pr=1483
```
failed to run git: fatal: not a git repository (or any of the parent directories): .git
```

🐛 Fix missing .git directory

---

policy/resolved_policy_builder.go

It is necessary for certain recalculations we do

Do not allow the space policy to be pruned

---

policy/resolved_policy_builder.go
policy/resolver_v2_test.go

Queries should not impact the score.  Only checks do that

ignore query score for controls

---

apps/cnspec/cmd/integrate.go
internal/onboarding/azure.go

This change adds a minimalistic preflight check where we verify that the user has the right role assignments to onboard an Azure environment.
We need one of "**Privileged Role Administrator**" or "**Global Administrator**"
https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#privileged-role-administrator
Note that we run Azure CLI commands directly so that `cnspec` doesn't have to import the entire Azure SDK which will make the binary much bigger, which today is unnecessary for the amount of checks we are running.

⭐️ integrate preflight check: role assignments

---

.github/workflows/pr-test-lint.yml

Use `mondoo-mergebot` app token when approving/merging PRs in order to avoid scenarios where we are attempting to create and approve a PR with the same user.

Avoid reviewing own PRs by auto-merging with bot token

---

.github/workflows/pr-test-lint.yml

This should fix:
https://github.com/mondoohq/cnspec/actions/runs/12136947927/job/33839326646
> only one of --merge, --rebase, or --squash can be enabled

🐛 Fix gh merge command

---

go.mod
go.sum
policy/executor/internal/nodes.go
policy/resolved_policy_builder.go
policy/resolver.go

This reports them as skipped for old clients, disabled for new clients. It does this by injecting a query which always reports a skipped score. Doing so allows us to know if an asset didn't run a query that would have because it is disabled

Report a score for disabled queries

---

policy/score_calculator.go
policy/score_calculator_test.go

It's possible for impact to be be nil, in which case we should use the default value which is 100. Using the score value doesn't make sense. It would mean that the category would change based on if it passed or failed in cases where impact was not defined.

🐛 Use 100 for the default value of impact

---

policy/executor/internal/collector.go
policy/executor/internal/execution_manager.go
policy/scan/local_scanner.go

The main cnspec goroutine has already a `recover()` statement, though Go doesn't
share that between goroutines and since the calculation of the policies happen on
another thread, we were not reporting upstream.

🚨 recover from panic's inside goroutines

---

test/providers/scan_flags_test.go

This changed since the `github` provider changed.
We still want to test that flags are loaded, so I am updating the test and not removing it.

🐛 fix CI test

---

internal/onboarding/azure.go

This fixes Mondoo not being able to scan VMs on Azure.

fix #1532, add missing azure permission

---

cli/reporter/print_compact.go

Adds the platform name to the asset name header in the asset section.
```
Asset: planetexpress
--------------------
```
becomes
```
Asset: (Arch Linux) planetexpress
---------------------------------
```
Fixes #1534

Add asset platform to cnspec output when displaying asset

---

cli/reporter/cli_reporter.go
cli/reporter/json.go
cli/reporter/json_test.go
cli/reporter/proto.go
cli/reporter/testdata/simple-report.json

The output was using an off-handed way of trying to determine if something is a check. The reporting job type has this exact information.
Fixes #1540

🐛 Let resolved policy tell you if something is a check

---

go.mod
go.sum
policy/executor/internal/execution_manager.go

requires https://github.com/mondoohq/cnquery/pull/5107

📝 report when query takes longer than 5 min to execute

---

.github/workflows/goreleaser.yml
.goreleaser.yml

Also migrate deprecated goreleaser syntax

Pin goreleaser version due to issue with rpm<=4.16

---

.github/workflows/gh-release.yaml
.github/workflows/goreleaser.yml

- increase timeout while waiting for the release files
- wait for the container which is needed for the next step
- create token which works across repos

:bug: Fix errors in client release pipeline

---

docs/development.md

https://github.com/mondoohq/cnspec/actions/runs/13004679114/job/36269400650
Looks like the link checker cannot follow redirects.

🐛 Fix broken links

---

policy/executor/internal/nodes.go
policy/resolved_policy_builder.go
policy/score.go

Report scores for snoozed checks with score type `Snoozed`

✨ add specific score type for snoozed checks

---

policy/executor/internal/nodes.go
policy/score.go

If we add a Snoozed type we potentially hide error scores. Instead of adding a new score type, we will solve the issue differently on the backend

🧹 don't add snoozed score type

---

cli/reporter/cli_reporter.go

I added this because our tests loaded these from a file. However, the more I think about it, its probably not a good idea to do this because it can get really large

🧹 Don't write report collection for debug output

---

.github/workflows/goreleaser.yml

Remove repository-dispatch event triggering a release to releases.mondoo.com. Releases will be entirely managed inside the [installer](https://github.com/mondoohq/installer/) repo in the future.

#498 BURP: Remove dispatch event for releases.mondoo.com

---

.github/.golangci.yml
.golangci.yml

This fixes https://github.com/mondoohq/cnspec/actions/runs/13894237360/job/38871321104\?pr\=1603
These are the same fixes as for cnquery.

🧹 Fix deprecated/removed/moved parameters for golangci

---

examples/complex.mql.yaml
internal/bundle/fmt.go
internal/bundle/lint.go
internal/bundle/lint_test.go
internal/bundle/testdata/unknown-field.mql.yaml

We found issues where remediations are not correctly set in policies. Seems like our linter does not enforce no unknown fileds to be present in the bundle. This PR changes that so now we can get:
```
cnspec policy lint mondoo-aws-security.mql.yaml
→ lint policy bundle file=mondoo-aws-security.mql.yaml
RULE ID         LEVEL  FILE                          LINE  MESSAGE                         
bundle-invalid  error  mondoo-aws-security.mql.yaml  1     cannot parse the yaml file      
mondoo-aws-security.mql.yaml:   
error unmarshaling JSON: while  
decoding JSON: json: unknown    
field "remediation"             
FTL invalid policy bundle
```
One limitation of this approach is that we do not get the exact line of the issue. This is better than nothing. A better solution that would yield the …

✨ extend policy linter to enforce no unknown fields in yaml

---

cli/reporter/print_compact.go

Its not valid to say anything but asset scoped risk factors are valid. The vuln report would need to tell you about the software scoped risk factors that apply. That information currently is not reported by `AssetVulnerabilityCompactReport`

Filter out risk factors that are not valid

---

policy/bundle.go
policy/resolver_v2_test.go

Makes the following example work. Not that you still need to declare you are going to use a property which is done by referencing the uid without any mql
```yaml
policies:
- uid: example1
name: Example policy 1
version: "1.0.0"
authors:
- name: Mondoo
email: hello@mondoo.com
groups:
- title: group1
filters: asset.family.contains("unix")
checks:
- uid: check-4
props:
- uid: adminaccount
mql: return "adminaccount"
queries:
- uid: check-4
title: check 4
mql: props.adminaccount == "foo"
filters: asset.family.contains("unix")
props:
- uid: adminaccount
```

Allow props to be set on policy

---

internal/onboarding/azure.go
internal/onboarding/azure_test.go

Improve our onboarding for azure to only add reader role to the selected subscriptions and
not all of them.
When we pass the `--allow` flag(s):
```bash
$ cnspec integrate azure --space epic-mclaren-654267 --allow 3cd8b376-ada6-4c01-afc3-84d4b7d7da9a --allow 8b7a5c6b-433b-4d12-baba-b4174f1e2fea
→ using space //captain.api.mondoo.app/spaces/epic-mclaren-654267
→ verifying role assignments for the currently logged-in user
→ user service principal ead44178-3739-4df5-bbcd-02b88de9d12a
→ role assignment Privileged Role Administrator found
→ generating automation code
→ integration name not provided, using subscription-84d4b7d7da9a
→ code stored at /Users/afiune/.config/mondoo/onboarding/azure
→ existing Terraform path /opt/homebrew/bin/terraform
→ existing Terraform version 1.8.5
→ using …
```

✨ onboarding: azure allow subscriptions

---

internal/datalakes/inmemory/assets.go
internal/datalakes/inmemory/policyhub.go
internal/datalakes/inmemory/policyresolver.go
policy/datalake.go
policy/hub.go
policy/policy.go
policy/policy_test.go
policy/resolver.go
policy/services.go

The execution checksum needs to change as time passes a groups start and end. This change returns to the caller when the checksum should be recomputed

Notify when a policy checksum must be recalculated

---

policy/rating.go

This is still used in some APIs

Add back letter grade

---

apps/cnspec/cmd/report.go
cli/reporter/cnspec_report.go
cli/reporter/cnspec_report_compare.go
cli/reporter/cnspec_report_compare_test.go
cli/reporter/testdata/cnspec_report_mixed.json
cli/reporter/testdata/cnspec_report_pass.json

We introduce a new experimental sub command to compare two different cnspec reports. First you can create a report via:
```bash
cnspec scan local --output json > cnspec_report.json
```
If you want to compare this report with an older one, just run `cnspec report cmp`
```bash
cnspec report cmp cli/reporter/testdata/cnspec_report_pass.json cli/reporter/testdata/cnspec_report_mixed.json
→ 🔍 comparing asset mac.fritz.box with mac.fritz.box
→ 🔴 check "//local.cnspec.io/run/local-execution/queries/mondoo-macos-security-reduce-the-sudo-timeout-period" got different results
→    expected:      {"score":100,"status":"pass"}
→    got     : {"status":"fail"}
→ ✅ reports are equal
```

⭐️ cnspec report compare

---

upstream/gql.go

This fixes the issue where `cnspec policy list -a` only returns 200 items, it will now return all of them.

🐛 Policy list -a limit fix

---

internal/onboarding/azure.go
internal/onboarding/azure_test.go
internal/tfgen/hcl.go
internal/tfgen/hcl_test.go

Customers are having issues onboarding subscriptons that are in a state other than `Enabled`.
This change only integrates with subscriptons that are enabled.
Contributes to https://github.com/mondoohq/cnspec/issues/1560

⭐️ onboarding: ignore non-enabled azure subscriptons

---

policy/executor/graph.go
policy/executor/internal/collector.go
policy/scan/local_scanner.go

No functional changes here, just making sure we provide the context to the `BufferedCollector` externally instead of creating a background context for every request

🧹 provide collector context externally

---

internal/onboarding/ms365.go
internal/onboarding/ms365_test.go

We are still experiencing more permission issues like:
```
cnspec> ms365.sharepointonline.defaultLinkPermission
access denied, please ensure the credentials have the right permissions in Azure AD
ms365.sharepointonline.defaultLinkPermission: null
```
and
```
cnspec> microsoft.security.secureScores
error while performing request. Code: UnknownError, Message: Auth token does not contain valid permissions or user does not have valid roles.
microsoft.security.secureScores: no data available
```
This PR is refactoring how we create all the necessary resources to grant
permissions to the Mondoo App Registration we deploy to scan Microsoft
365 tenants. 
The refactor will make it easy for us visualize (human-readable) permissions
and automatically create the necessary resources in Terraform to …

⚙️  onboarding: refactor ms365 permissions

---

policy/bundle.go
policy/bundle_test.go

The order in which the bundle is compiled has changed, which meant the old field was not properly being migrated

🧹 Migrate deprecated Query field on Mquery

---

content/chef-infra-server.mql.yaml
content/mondoo-http-security.mql.yaml
content/mondoo-linux-security.mql.yaml

I noticed a lot of our steps didn't work for my Debian system because the config was already set in the /etc/sysctl.conf file. If it's there let's make sure to edit it. If not then we can create the .d file
I also confirmed that a reload of auditd does not load the main config file so if you change that you need to do a full restart.
Finally I nuked some sudo usage in our remediations so things are consistent

Improve logic in sysctl remediations + improve auditd remediation

---

Makefile

This lets us do:
```sh
LDFLAGSEXTRA="-X go.mondoo.com/cnquery/v11.DisableMaxLimitSize=true" make cnspec/build/linux
```

✨ Allow injecting ldflags to the build targets.

---

.gitignore
apps/cnspec/cmd/scan.go
apps/cnspec/cmd/vuln.go
cli/reporter/cli_reporter.go
cli/reporter/cli_reporter_test.go
cli/reporter/file_handler.go
cli/reporter/output_handler.go
cli/reporter/print_compact.go
test/cli/testdata/cnspec_scan.ct

We are moving away from the old score system (0 = critical, 100 = info) to the risk-based scoring mechanism. For that purpose we are deprecating `--score-threshold` and moving to `--risk-threshold`. Also, the new `--risk-threshold` has a more consistent UX.
For example, let's say you want to fail a pipeline scan on critical findings. The old way: 
```
cnspec scan --score-threshold 11
```
and the new way:
```
cnspec scan --risk-threshold 90
```
The new number is inclusive i.e. risk 90-100 is critical, setting the threshold there will make it error once the number is reached.

⭐ migrate --score-threshold to --risk-threshold

---

policy/cnspec_policy.pb.go
policy/cnspec_policy.proto
policy/cnspec_policy_vtproto.pb.go
policy/resolved_policy.go
policy/scan/local_scanner.go

This allows the server to set or unset certain features that it supports. This means e.g. that if the server can store resources data in the new format, we can send it this way.

⭐ add support for server-side features

---

.github/workflows/goreleaser.yml

Trigger the final release job only if we are not on a pre-release ref (`-pre`)

fix(ci): Skip installer dispatch hook on pre-release versions
