.github/workflows/goreleaser.yml, .github/workflows/pr-test-lint.yml, docs/development.md
=> 🧹 remove the github setup for private repos in actions

README.md
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>
=> 🧹 add link to policy bundles

internal/plugin/plugin.go
=> 🧹 avoid using sh to launch cnquery

apps/cnspec/cmd/shell.go
=> 🐛 temporary workaround for mondoo.version in shell

cli/reporter/print_compact.go
Provide more of a score distribution in the result view:
This communicates better how many critical vs minor results were detected.
=> 🌈 colorful score distribution

apps/cnspec/cmd/root.go, apps/gen-docs/main.go
adjusted to cnquery updates. This should rather be shared functions for all CLIs later on ;)
=> ✨ metadata in cli docs + no duplicate headers

apps/cnspec/cmd/bundle.go, apps/cnspec/cmd/root.go, apps/cnspec/cmd/scan.go
=> Uppercase more help lines

go.mod, go.sum, policy/executor/executor.go, policy/executor/executor_test.go, policy/executor/graph.go, policy/executor/mustcompile.go, policy/mquery.go
brings over the improvements from https://github.com/mondoohq/cnquery/pull/302 to cnspec
=> ✨ easier configuration for the compiler

policy/bundle_test.go, policy/policy_test.go
This was missed due to #122 missing to run the tests. Will look into the test coverage on PRs in this repo.
=> 🐛 restore paths to test files

apps/cnspec/cmd/bundle.go
With this changed, authenticated users can upload policy bundles to Mondoo Platform
```
$ cnspec bundle upload example-policy.mql.yaml
→ loaded configuration from /Users/chris/.config/mondoo/mondoo.yml using source default
→ load policy bundle file=example-policy.mql.yaml
→ valid policy bundle
→ add policy bundle to space space=//captain.api.mondoo.app/spaces/musing-saha-952142
→ successfully added policies
```
=> ⭐️ allow user to upload policy bundles to query hub

.github/workflows/goreleaser.yml, .goreleaser.yml, Dockerfile
=> ⭐ Add container image

.github/actions/spelling/expect.txt, README.md
=> Fix a typo & cleanup the dictionary

.github/actions/spelling/line_forbidden.patterns, README.md
=> Readme typo updates + spellcheck  updates

.vscode/launch.json, policy/scan/local_scanner.go
=> 🐛 Access original data send back by server

apps/cnspec/cmd/scan.go
much like we do for cnquery, https://github.com/mondoohq/cnquery/pull/431/files
=> 🧹 add cnspec version and build to client headers on upstream scan

apps/cnspec/cmd/login.go, apps/cnspec/cmd/root.go, apps/cnspec/cmd/scan.go
=> 🐛 fix cnspec build

policy/scan/local_scanner.go
it was printing into JSON output, try not to do that
=> 🐛 avoid progressbar on non-interactive CLI

.vscode/launch.json, cli/progress/progress.go, go.mod, go.sum
=> Update bubbletea package. Reenable TTY detection

policy/scan/aggregate_reporter.go, policy/scan/error_reporter.go
I noticed that 2 of the properties of the `ScanResult` are not set. This PR fixes that
=> 🐛 Set WorstScore and Ok for scan API results

go.mod, go.sum
This change depends on https://github.com/mondoohq/cnquery/pull/499
=> 🧹 update to cnquery 7.5.0 and downgrade to cty 1.10.0

apps/cnspec/cmd/scan.go, go.mod, go.sum
Follow-up to the cnquery changes, allows cnspec scanning to set the asset name.
=> ✨Add --asset-name flag for scanning.

.github/actions/spelling/line_forbidden.patterns, .github/workflows/spell-check.yaml
=> Add more match patterns to spellcheck

cli/reporter/print_compact.go, cli/reporter/print_darwin.go, cli/reporter/print_linux.go, cli/reporter/print_report.go, cli/reporter/print_windows.go, cli/reporter/render_advisory_policy.go, cli/reporter/render_asset_overview.go, cli/reporter/render_meta_policy.go, cli/reporter/render_policy.go, cli/reporter/summary.go
=> 🐛 Fix CLI output on Windows

go.mod, go.sum
=> 🧹 Bump cnquery

policy/executor/executor.go, policy/executor/executor_test.go, policy/executor/internal/builder.go
We had a few more still floating around
=> Replace Mondoo Client with cnspec in errors

apps/cnspec/cmd/scan.go
Same fix that was done here https://github.com/mondoohq/cnquery/pull/535
=> Fix --incognito flag warning

apps/cnspec/cmd/login.go, apps/cnspec/cmd/root.go, apps/cnspec/cmd/vuln.go, cli/components/advisory_results.go, cli/reporter/print_report.go, cli/reporter/render_meta_policy.go, cli/reporter/summary.go, internal/datalakes/inmemory/policyhub.go, internal/datalakes/inmemory/resolved_policy_cache.go, policy/bundle.go, policy/cnspec_policy.pb.go, policy/collectorjob.go, policy/executor/executor.go, policy/executor/internal/builder.go, policy/executor/internal/nodes.go, policy/hub.go, policy/policy.go, policy/resolver.go
=> More spelling fixes

policy/scan/local_scanner.go
Failed to sync where?
Before:
```
→ loaded configuration from /Users/tsmith/.config/mondoo/luna.yml using source --config
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
→ connecting to asset Lunalectric/frontend (api)
x failed to synchronize asset  error="rpc error: code = Unauthenticated desc = request permission unauthenticated"
```
Now:
```
→ loaded configuration from /Users/tsmith/.config/mondoo/luna.yml using source --config
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
→ connecting to asset Lunalectric/frontend (api)
x failed to synchronize asset to Mondoo Platform  error="rpc error: code = Unauthenticated desc = request permission unauthenticated"
``` …
=> Improve failed to sync asset error message

apps/cnspec/cmd/scan.go, cli/reporter/print_report.go, cli/reporter/render_meta_policy.go, policy/resolver.go, policy/scan/local_scanner.go
=> Fix spelling of policies

apps/cnspec/cmd/shell.go, apps/cnspec/cmd/vuln.go
=> Replace a few Mondoo references with cnspec

README.md, apps/cnspec/cmd/login.go, apps/cnspec/cmd/run.go, apps/cnspec/cmd/scan.go, apps/cnspec/cmd/shell.go, apps/cnspec/cmd/vuln.go
A lot of this is sync from cnquery and syncing each subcommand to make sure we have consistent help everywhere.
=> Add missing help descriptions + rework descriptions

.github/.goreleaser-edge.yml
Successful build https://github.com/mondoohq/cnspec/actions/runs/3787331889
=> 🐛 Fix edge release typos

README.md
The README file already contains mention of the Mondoo Platform. This expands the section for clarity.
Signed-off-by: Charles Johnson <chip@mondoo.com>
=> Update the Mondoo Platform section of README.md

README.md
Manifest not machine and give a manifest example
=> Update the k8s scan example

cli/reporter/reporter.go
=> ✨ support YAML output format

internal/bundle/lint.go
Make these a bit more consistent
=> 🧹 Rework some of the policy lint checks

cli/reporter/print_compact.go
fixes #265
This bug was introduced in #263
=> 🐛 fix nil pointer error in cli reporter

cli/reporter/print_compact.go
=> 🧹 Remove unimplemented command from output

cli/reporter/print_compact.go
=> 🧹 Skip unscored when not present

cli/reporter/print_compact.go, go.mod, go.sum
We already use this lib in cnquery. The other one was an additional dependency
=> 🧹 Use other lib to calculate width

policy/scan/local_scanner.go
=> 🧹 Revert special handling of CI/CD platformID

.vscode/launch.json, cli/reporter/print_compact.go
=> 🐛 Fix summary when an error happend during scan

cli/reporter/print_compact.go
Worked with Letha to improve these text
=> Update the copy presented post scan

go.mod, go.sum
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>
=> 🧹 update to cnquery 7.12.1

.github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/reject.txt
Match cnquery to avoid common mistakes
=> Update our spellcheck terms

cli/reporter/print_compact.go, policy/scan/aggregate_reporter.go
=> 🐛 Summary didn't show assets with errors

.vscode/launch.json, apps/cnspec/cmd/bundle.go, apps/cnspec/cmd/login.go, apps/cnspec/cmd/logout.go, apps/cnspec/cmd/root.go, apps/cnspec/cmd/scan.go, apps/cnspec/cmd/serve_api.go, apps/cnspec/cmd/status.go
=> 🐛 Fix panic for malformed credentials

.goreleaser.yml
=> 🐛 Fix conflicting file with mondoo client package

go.mod, go.sum, policy/executor/graph.go, policy/executor/internal/builder.go, policy/executor/internal/builder_test.go, policy/executor/internal/nodes.go, policy/executor/internal/nodes_test.go, policy/scan/local_scanner.go, policy/scan/scan.go
This depends on https://github.com/mondoohq/cnquery/pull/831
=> 🧹 Use the refactored multiprogress

policy/scan/local_scanner.go
=> 🐛 Handle motor/sync error for progress bar

go.mod, go.sum, policy/scan/local_scanner.go
=> 🧹 Hide progressbars when debug logging is enabled

go.mod, go.sum, policy/scan/local_scanner.go
=> 🌈 Use full-width progress bar

policy/scan/local_scanner.go
=> 🧹 Refactor job error reporting

go.mod, go.sum
Signed-off-by: Ivan Milchev <ivan@mondoo.com>
=> 🧹 Update cnquery

examples/example.deprecated_v7.mql.yaml
=> 🐛 update examples to v8 syntax

policy/deprecated_v7.go
This helps with the migration of old v7 structs used in other places. So
far this method was not re-usable. Making it accessible helps with other
places that need to migrate scoring specs.
=> 🧹 make scoringspec v7=>v8 accessible

policy/collectorjob_test.go
which for some reason was missing
=> 🧹 migrate over collectorjob_test

cli/reporter/print_compact.go
Fixes https://github.com/mondoohq/cnspec/issues/169
=> 🐛 add consistent indication to passed scores

apps/cnspec/cmd/vault.go
https://github.com/mondoohq/cnquery/pull/893 to cnspec v7
=> ⭐️ vault subcommand to manage vaults

apps/cnspec/cmd/vuln.go, go.mod, go.sum, policy/scan/local_scanner.go
After https://github.com/mondoohq/cnquery/pull/899
=> 🧹Update usage of inventory manager api

.github/actions/spelling/expect.txt, .github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/patterns.txt
Remove some overly broad rules
=> Update spellcheck patterns

internal/datalakes/inmemory/policyresolver.go
The SetProps call didn't update checksums. There was also no way to delete a property. 
Since the call is only used when property values (i.e. the MQL) is set, we can remove properties if they are called with the set call but no MQL is provided. This call doesn't make sense when not used for overriding values, since all other policy- or query-based properties are embedded and don't use this call.
=> 🐛 setting properties updates the checksums

policy/bundle.go, policy/deprecated_v7.go
a few helpers to convert bundles and add v7 policies to them
=> 🧹 more v7 compatibility conversion helpers

policy/hub.go
allows us to set policies (with optional bundle) and entire bundle maps directly
=> 🧹 expose set policy from bundle calls

policy/bundle_map.go, policy/deprecated_v7.go, policy/mquery.go, policy/reportingjob.go, policy/resolver.go
and also start to re-use sortedKeys in a few other places to sort keys
=> 🐛 stabilize the order of v7 conversions

policy/deprecated_v7.go
Convert v8 policies back into v7 for compatibility. Also add a method to fill fields in bundles for v7 compatibility.
=> 🧹 v7 policy convertors

policy/policy.go
... if they are not in the bundle
=> 🐛 look up checks and queries from upstream

policy/bundle.go, policy/bundle_map.go, policy/policy.go
these were missing and left UIDs in the policies
=> 🐛 translate policy ref UIDs

policy/hub.go
switches cnspec to use the new registry
=> ⭐️ switch to new registry

README.md, docs/development.md
add and change doc links
reduce marketing voice and wordiness a bit
consistency and style changes
=> 📄 readme edits

.github/.goreleaser-edge.yml
Another small typo in the UBI release for edge
=> 🐛 fix release of edge UBI containers

.github/workflows/goreleaser.yml
Refer to https://github.com/mondoohq/releasr#releasr for more details.
=> ⭐️ Invoke releasr after build

cli/reporter/print_compact.go, examples/example.mql.yaml, go.mod, go.sum, policy/deprecated_v7.go, policy/reportingjob.go, policy/resolver.go, policy/score_calculator.go, policy/score_calculator_test.go
see https://github.com/mondoohq/cnquery/pull/1010
=> 🧹 adjust to cnquery impact changes

policy/deprecated_v7.go
Props were so far only loaded from raw v7 bundles, which generally use UIDs instead of MRNs. However, it didn't work on processed v7 bundles (like validated and compiled bundles) which are using MRNs instead.
Additionally, we were dragging around the properties field in policies, which in v7 only served to provide props to queries, but didn't do anything else (e.g. wiring / overrides). Because we can now directly embed properties into queries, we can fully remove them from policies during the conversion process.
To make the analysis less brittle, we now look for the basename of MRN properties (instead of a specific resource in the MRN). This is in line with v7 behavior, which also puts the name at the end.
=> 🐛 fix v7 custom bundle loading

examples/example.mql.yaml
Fixed typos
Made comments more readable
=> 🧹  edited example bundle comments, changed one check

policy/bundle.go
My previous pr https://github.com/mondoohq/cnspec/pull/425 introduced an error that merged base queries into their parents, which caused any updates to base queries not get registered as a change. This PR fixes the issue by keeping track of a merged query object during the compile step, which avoids writing unnecessary information into the policy/group check or query.
=> 🐛 avoid accidentally merging queries in compile phase

.github/actions/spelling/README.md, .github/actions/spelling/advice.md, .github/actions/spelling/expect.txt, .github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/patterns.txt, .github/actions/spelling/reject.txt
Use the current set of patterns
=> Update set of spellcheck patterns

go.mod, go.sum, policy/resolver.go, policy/resolver_test.go
Only after https://github.com/mondoohq/cnquery/pull/1081 + update to go deps.
=> 🧹 re-use cnquery AssetMatchError + add resolver tests

internal/bundle/lint.go, internal/bundle/lint_test.go, internal/bundle/testdata/failing_lint.mql.yaml
- uses new groups for liniting
- supports embedded queries
=> 🐛 adjust linting to v8 policy structure

internal/bundle/bundle.yac.go, internal/bundle/bundle_test.go, internal/bundle/fmt.go, internal/bundle/fmt_test.go, internal/bundle/yacit/main.go, internal/yac-it/yac-it.go
- handle case where v7 structs where loaded in v8 parse
- order fields for yaml formatting
=> 🐛 bundle fmt

.github/workflows/goreleaser.yml, .goreleaser.yml
For details of the method, please refer to https://github.com/mondoohq/mac-signer
=> Sign and Notarize Mac Binaries

policy/resolver_test.go
Add unit test to check policies which gets modified with action "IGNORE".
=> 🧹 Add test for policy with ignore action

policy/resolver.go, policy/resolver_test.go
The policy groups had an end date added, but we never wired the resolver up to look at that field when making the resolved policy
=> ⭐️ Make policy resolver take the end date of groups into account

README.md
simplifies the installation instructions
=> 🧹 update install instructions for cnspec

policy/policy.go, policy/policy_test.go
The execution checksum was only taking into account the code id of the query that specified it had variants. This wasn't changing if one of the variants since that query itself has no code.
=> 🐛 Fix checksumming of policies with variants

policy/bundle.go
There are many paths in which the UID is zero'd out if a MRN is calculated. Instead, the detection is moved to a point at which MRNs have been calculated, but before any compilation of queries happens
=> 🐛 Use MRNs for variant cycle detection

policy/scan/local_scanner.go
If there's a present config, use it even with the incognito flag. That lets cnspec communicate upstream to analyze assets (if needed).
The missing endpoint and space mrn checks are now only done if cnspec is not running incognito since then it is assumed that those will not be needed, thus checking for them does not make sense.
The following will work:
`cnspec scan container fedora:31 --incognito`
`cnspec scan container fedora:31 --incognito --config bad-config`
=> 🐛 Initialize endpoint and client when using incognito.

apps/cnspec/cmd/scan.go
so it is clear this is getting uploaded over the internet and not a local browser view
=> reword the upload quesiton

cli/reporter/print_compact.go, cli/reporter/reporter_test.go
=> ✨ Align output of checks

apps/cnspec/cmd/scan.go
Clarifies the help message for the share-report flag
=> Updates help for share-report flag

cli/reporter/print_compact.go
Minor update to clarify output formatting now that the report service exists
=> Updates output formatting help text

policy/bundle.go
=> ⭐️ propagate props from base to variants so we do not have to define multiple times

apps/cnspec/cmd/scan.go, apps/cnspec/cmd/shell.go
related to the addition of OCI https://github.com/mondoohq/cnquery/pull/1190 in cnquery
=> 🧹 add help text for OCI tenancy

internal/bundle/lint.go, internal/bundle/lint_test.go
=> 🐛 Fix linting of examples/complex.mql.yaml

internal/datalakes/inmemory/policyresolver.go, policy/resolver.go
The `AssignmentDelta_Action` did not have all the values, i.e. `IGNORE` which is used to for previewing a policy
=> Use explorer.Action for MutateAssignments

apps/cnspec/cmd/scan.go
Helps diagnose performance issues
=> 🧹 Initialize the profiler from cnquery

docs/development.md
see https://github.com/mondoohq/cnquery/pull/1273
=> 📃 add indicator for commits that improve performance

apps/cnspec/cmd/bundle.go, apps/cnspec/cmd/login.go, apps/cnspec/cmd/logout.go, apps/cnspec/cmd/migrate.go, apps/cnspec/cmd/run.go, apps/cnspec/cmd/scan.go, apps/cnspec/cmd/serve.go, apps/cnspec/cmd/serve_api.go, apps/cnspec/cmd/shell.go, apps/cnspec/cmd/status.go, apps/cnspec/cmd/vault.go
=> 🐛 Add missing help docs

.github/actions/spelling/advice.md, .github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/patterns.txt
=> Update spellcheck pattern matches

README.md
=> Fix platforms and some help output in readme

examples/compliance.mql.yaml
Exceptions cannot be managed inline with the framework in this manner.
=> 🧹 Modify example compliance.mql.yaml to be compatible with Mondoo cloud

internal/bundle/fmt.go
This further improves the bundle formatter to handle trailing whitespace. Trailing whitespace is the main reason the formatter outputs strings as quoted strings. This addresses this issue for more fields in the yaml format.
=> 🧹 improve bundle formatter to handle trailing whitespace

policy/resolver.go, policy/resolver_test.go
When we have controls that map to check, the resolver creates a reporting job from the query by its code id to query by its mrn. And then maps that to the control. However, there was a bug in this translation where we would pick a random check mrn from the bundle that had that code id. Since its possible for multiple checks to have the same id in a bundle, and not all of those checks are part of an active policy, this would end up picking a mrn from a policy that wasn't active.
=> 🐛 Fix check control resolver bug

.github/workflows/pr-test-lint.yml, apps/cnspec/cmd/vault.go, go.mod, go.sum
brings https://github.com/mondoohq/cnquery/pull/1500 to cnspec
=> 🧹 remove internal vault since it is easier to configure via inventory file

apps/cnspec/cmd/root.go, apps/cnspec/cmd/scan.go, policy/scan/local_scanner.go
- shell + run + scan did not attach providers at all; added
- scan had a list of copy-paste mistakes from cnquery (where it referenced querypacks instead of policies)
- scanning did not work, the first succesful scan is now executed
=> 🐛 fix cnspec scan

apps/cnspec/cmd/scan.go
=> 🐛 restore score-threshold

.github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/reject.txt, .github/dependabot.yml, .github/workflows/spell-check.yaml
=> Update to the latest spellcheck GH Action

apps/cnspec/cmd/serve.go, policy/scan/local_scanner.go
depends on cnquery https://github.com/mondoohq/cnquery/pull/2015
=> ⚡ re-use runtimes across providers

apps/cnspec/cmd/root.go, apps/cnspec/cmd/vuln.go
https://github.com/mondoohq/cnspec/issues/754
```
~/go/src/go.mondoo.io/cnspec vj/vulncmd-migration*
[2/10/23 08:38:19] ❯ DEBUG=1 go run apps/cnspec/cnspec.go vuln container b2983204711d
DBG searching providers in path path=/Library/Mondoo/providers
DBG searching providers in path path=/Users/vj/.config/mondoo/providers
DBG Started a new runtime (1 total)
DBG using provider os with connector container
DBG Started a new runtime (2 total)
DBG no need to update provider last-refresh=16m56.515295s provider=os
DBG running provider plugin path=/Users/vj/.config/mondoo/providers/os/os
→ loaded configuration from /Users/vj/.config/mondoo/mondoo.yml using source default
DBG starting query execution qrid=aqEqEJNmLWE=
DBG …
```
=> 🧹 migrate vuln cmd from v8

policy/scan/local_scanner.go
Running scans in parallel causes issues with killing providers from previous scans. This is a temporary fix for the scan API such that only 1 scan runs at a time. We can re-write the code to kill only the specific provider used in the current scan, instead of all providers at a later stage.
Running 1 scan at a time isn't really an issue at the moment since only the `mondoo-operator` is using the scan API. There we always run 1 cluster scan at a time. The things that could run next to it are single resource scans that are coming via the internal queue. They are not time-sensitive and aren't blocking anything.
=> 🧹 run 1 scan at a time via scan API

apps/cnspec/cmd/scan.go, cli/reporter/json.go, cli/reporter/reporter_test.go, cli/reporter/testdata/report-k8s.json
=> 🐛 Prevent panic in json output when all assets errored

Makefile
https://goreleaser.com/deprecations/\#-skip
=> 🧹 Fix deprecated goreleaser flags

apps/cnspec/cmd/root.go
We updated this in v8 a while back
=> Update the cnspec tagline to match v8

cli/reporter/reporter.go
This enables CLI + upstream reporting again
=> 🐛 hotfix vulnerability reporting

apps/cnspec/cmd/bundle.go
for linting and formatting we need the providers available locally. Therefore we just install them all before we run the task.
```
$ cnspec bundle lint ./policies
→ lint policy bundle file=./policies
→ installing provider 'terraform' version=9.0.15
→ successfully installed terraform provider path=/Users/chris/.config/mondoo/providers/terraform version=9.0.15
→ installing provider 'arista' version=9.0.7
→ successfully installed arista provider path=/Users/chris/.config/mondoo/providers/arista version=9.0.7
→ installing provider 'atlassian' version=9.0.2
→ successfully installed atlassian provider path=/Users/chris/.config/mondoo/providers/atlassian version=9.0.2
→ installing provider 'ms365' version=9.0.10
→ successfully installed ms365 provider …
```
=> ⭐️ install provider before lint and fmt

apps/cnspec/cmd/scan.go, policy/scan/local_scanner.go
Closes #858 
```
cnspec scan ssh root@192.168.122.158 --ask-pass --config demo.agent.credentials.json --asset-name IAMTHEASSETNAMENOW
```
And here the result in console:
=> 🐛 fix --asset-name flag

policy/scan/local_scanner.go, policy/scan/local_scanner_test.go, policy/scan/testdata/2pods.yaml
This field is needed for garbage collection.
Fixes https://github.com/mondoohq/mondoo-operator/issues/893
=> 🐛 Add ManagedBy to assets

policy/bundle.go, policy/policy_test.go
Makes for looking through a problematic bundle easier
=> 🧹 Include mrn in ErrVariantCycleDetected.

policy/scan/fetcher.go
=> 🐛 Filter out queries with compilation issues w/ pub registry

policy/resolver_test.go
Not sure if this is the best way to write that test, but only way I could have it get an asset policy with the ignored check in.
=> Add a test for resolving a policy with an ignored query.

apps/cnspec/cmd/bundle.go, internal/bundle/fmt.go, internal/bundle/fmt_test.go, policy/bundle.go
Add a `--sort` flag to the `bundle fmt` cmd. It's optional and if passed will use the sort the selected fields.
Add `SortContentsV2` which makes bundle sorting a bit more extensible + a test
=> ✨Add sort flag to bundle fmt. Add SortContentsV2.

policy/scan/local_scanner.go
don't call `SynchronizeAssets` once when the assets are discovered and then another time before scanning each asset. That seems unnecessary. I ran a few tests with MacOS and Kubernetes and it seems like this changes nothing. Would be nice if other people can test it too
=> 🧹 do not call SynchronizeAssets twice

policy/report.go, policy/report_test.go
This allows me to add aggregated scores more efficiently to those structs.
=> 🧹 Add batch stat APIs

policy/resolver.go, policy/resolver_test.go
The issues here is the way policies are selected to be included. It checks this field called ComputedFilters of the policy. I'm not 100% sure what this is, but from the comment, it sounds like this has any filter that this policy uses. However, I don't think that is useful to answer the question of whether the policy should be included. For example, I run arch linux. If I include the alma linux 8 cis benchmark, that policy is included. That is because the following query is defined:
```
- uid: cis-almalinux-8--4.2.11
title: Ensure sshd KexAlgorithms is configured
impact: 100
filters: |
file("/etc/crypto-policies/config").exists == false
command('update-crypto-policies --show').stdout.trim == ""
...
```
This change fixes the problem by pruning out any reporting job nodes that are policies …
=> 🐛 Fix issue with policies matching against incorrect platforms

apps/cnspec/cmd/update.go
This PR adds the experimental update command to cnspec
```
cnspec update
```
It download the install script and runs it locally.
=> ⭐️ experimental update sub-command

apps/cnspec/cnspec.go
applies the cnquery panic handler to cnspec as well, see https://github.com/mondoohq/cnquery/pull/2963
=> ⭐️ panic handler to report panics

internal/bundle/fmt.go, internal/bundle/fmt_test.go
- replace tabs and /r with /n
- ensure x00 is not used
=> 🧹 make bundle fmt more robust and sanitize policy docs content as well as properties

.github/workflows/test-report.yml
add a test reporting step similar to what we have in cnquery
=> 🧹 add test reporting

cli/reporter/azure_service_bus_handler.go, go.mod
See https://github.com/google/go-cloud/issues/3378 for more details as to why.
=> 🧹 Use azservicebus sdk instead of the go-cloud one for sending a message

.github/pr-body.md, .github/workflows/cnquery-update.yml
A new cnquery release triggers this workflow to create a PR which updates the dep.
=> ✨ Automatically create cnquery update PR

go.mod, go.sum, policy/scan/local_scanner.go, policy/scan/local_scanner_test.go
use the new functionality exposed in mondoohq/cnquery#3202
=> 🧹 refactor local scanner code

.github/workflows/cnquery-update.yml
This brings the manual bump task to cnspec
=> ⭐️ add workflow_dispatch to cnquery bump action

.github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/patterns.txt
Flag more tech names + whitelist/blacklist
=> Expand terms we flag in the spellcheck

apps/cnspec/cmd/scan.go, apps/cnspec/cmd/serve.go
Requires https://github.com/mondoohq/cnquery/pull/3406 to turn green
=> 🐛 Set asset annotations during cnspec serve.

apps/cnspec/cmd/vuln.go, go.mod, go.sum
depends on https://github.com/mondoohq/cnquery/pull/3533
This PR refactors the data gathering and uses cnquery bom data gathering instead. This simplifies the code and reduces the different ways we gather data.
=> 🧹 use bom for vuln scanning

policy/risk_factor.go, policy/risk_factor_test.go
no need to return values, we can just adjust the score directly
=> 🧹 AdjustScore builds risk factor results into score

apps/cnspec/cmd/vuln.go
requires https://github.com/mondoohq/cnquery/pull/3616
=> ⭐️ use running kernel version for vuln analysis

.github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/patterns.txt, .github/workflows/cla.yaml, .github/workflows/link-check.yaml, README.md
- Fix a few typos
- Remove a dead link to the website
- Update the spellcheck config
- Update the supported platform
- Update the copyright year
- Add a dead link checking GHA
=> Readme + spellcheck updates + dead link GHA

policy/policy.go, policy/risk_factor.go, policy/risk_factor_test.go
This now includes all fields and separates the checksum between the execution and content part. The RiskFactor itself only tracks the content checksum, while we use the execution checksum when we calculate the policy checksum.
Particularly this last part was missing from risk calculations and cause the policy content/execution checksums to not get updated.
I also cleaned up a weird for-loop in the referenced policies checksum calculation.
=> 🐛 extend risk factor checksum calculation

apps/cnspec/cmd/backgroundjob/serve_unix.go, apps/cnspec/cmd/backgroundjob/serve_windows.go
Gain more insights when looking at `cnspec serve` logs on when certain actions have occurred.
=> ⚙️ Log current time when running cnspec serve.

policy/evidence.go, policy/evidence_test.go
Add support for referencing evidence by MRN.
* If a check/query in the evidence section has the `mrn` set, we do not put this into the newly generated policy. Instead we assume that there's a policy in the bundle that will have this query set.
* This means that we can now have a case where there's no policy being generated. If the evidence section references *only* MRNs, we don't need a policy
* Add tests for the cases above
To test locally, use :
```
policies:
- uid: example1
name: Example policy 1
version: 1.0.0
authors:
- name: Mondoo
email: hello@mondoo.com
groups:
- filters: asset.family.contains('unix')
checks:
- uid: test
mrn: //policy.api.mondo.app/queries/test
filters: asset.family.contains('unix')
mql: 2 > 1
frameworks:
- uid: compliance-x
name: My custom Compliance Framework …
```
=> ✨ Add support for referencing control evidence by MRN.

apps/cnspec/cmd/policy-example.mql.yaml
adjust the filter to the new style and add some desc to the example policy
=> adjust the asset filter to the new style

.github/workflows/goreleaser.yml
=> change workflow being triggered for installer release

policy/resolver_test.go
This tests shows, that MQL filters are OR connected.
=> 🧹 Add test for filters

apps/cnspec/cmd/serve.go
follow-up on https://github.com/mondoohq/cnquery/pull/3940
=> enable inventory templates for `serve` command

cli/components/advisories/report.go, cli/components/barchart.go, cli/reporter/json.go, cli/reporter/json_vuln_test.go, cli/reporter/render_advisory_policy.go, internal/datalakes/inmemory/policyhub.go, policy/executor/internal/nodes.go, policy/executor/internal/nodes_test.go, policy/resolver.go, policy/resolver_test.go, upstream/gql.go
Nothing user impacting here. Just some minor cleanup
=> Correct minor typos in variables / comments

.github/workflows/pr-test-lint.yml
Fixes:
https://github.com/mondoohq/cnspec/actions/runs/9936661630/workflow
=> 🐛 Fix wrong id field

go.mod, go.sum
The `disabled` state was not present, failing the cnspec build.
=> 🐛 Bump mondoo-go to include framework states.

apps/cnspec/cmd/policy-example.mql.yaml, examples/complex.mql.yaml, examples/directory/queries/sshd-01.mql.yaml, examples/directory/queries/sshd-02.mql.yaml, examples/directory/queries/sshd-03.mql.yaml, examples/example.mql.yaml, internal/bundle/testdata/failing_lint.mql.yaml
Updates MQL queries to use the new syntax
=> 🧹 update mql syntax

cli/reporter/proto.go, go.mod, go.sum
Follow-up to https://github.com/mondoohq/cnquery/pull/4401
=> ✨ Add labels to the reporter assets.

policy/resolver.go, policy/resolver_test.go
The issue with the current code is that all variant queries would get all MRN of other variant queries. That is because we index the mrn by codeid and variant queries all have the same codeid since they have no mql block. This PR makes sure a variant query gets the mrn of itself only
=> 🐛 make sure reporting job mrns work correctly for variants

apps/cnspec/cmd/serve.go
=> 🐛 Don't check for updates for the sbom provider

apps/cnspec/cmd/serve.go
we cannot set the log level for the serve mode. This pr makes sure we can set log level
=> 🧹 fix serve logging

.github/workflows/pr-test-lint.yml
This will automatically approve PRs like https://github.com/mondoohq/cnspec/pull/1475
=> 🤖 Auto approve cnquery bump PRs

apps/cnspec/cmd/backgroundjob/serve_windows.go
the previous pr didn't fix the flag which is now inverted
=> 🐛 fix win service check

policy/resolved_policy_builder.go
It doesn't make sense as the root is reusable
=> Do not add MRNs to the root

.github/actions/spelling/line_forbidden.patterns
=> Expand our spellcheck forbidden patterns

.github/workflows/gh-release.yaml
That should fix the color of these notifications:
=> 🐛 Fix Slack notification color

README.md
=> 🧹 update readme copyright

apps/cnspec/cmd/scan.go, test/cli/testdata/cnspec_scan.ct
=> Fix an extra space in help output

cli/reporter/print_compact.go
=> Improve the risk factors text in cnspec

apps/cnspec/cmd/scan.go, test/cli/testdata/cnspec_scan.ct
I was confused how to use this and had to pass it bogus data in order to find out how via the error message. Let's avoid that pain with a better help string
=> Better document how to use the annotation flag

apps/cnspec/cmd/vuln.go, test/cli/testdata/cnspec_vuln.ct
Fixes the `cnspec vuln --output json`
=> 🐛 set viper output flag

policy/risk_factor.go, policy/risk_factor_test.go
Its default starting out as 0 and needs to start off as the base score
=> 🐛 Initialize risk score before adjusting it

internal/bundle/lint.go, internal/bundle/lint_checks_policy.go, internal/bundle/lint_checks_queries.go, internal/bundle/lint_results_cli.go, internal/bundle/lint_test.go, policy/fmt/fmt.go, policy/tooling/tooling.go, policy/tooling/tooling_test.go
This simplifies the linter code and makes it more understandable.
=> 🧹 simplify linter code

.github/actions/spelling/excludes.txt, .github/actions/spelling/expect.txt, .github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/patterns.txt, .github/workflows/spell-check.yaml, content/mondoo-macos-security.mql.yaml
Update this repo to the latest and greatest
=> Update to our latest spellcheck config for policies

.github/workflows/pr-test-lint.yml
That should fix: https://github.com/mondoohq/cnspec/actions/runs/15560718430/job/43813252563\?pr\=1691
=> 🧹 Set job specific provider path

.github/workflows/policies_lint.yaml, content/vulnerabilities/mondoo-k8s-nginx-ingress-vulnerability.mql.yaml
There were issues firing the policy linting
=> Add policy linting

.github/actions/spelling/line_forbidden.patterns, content/mondoo-linux-security.mql.yaml
More remediation step improvements
=> ⭐ Improve remediation steps in Mondoo Linux Security

apps/cnspec/cmd/integrate.go, policy/scan/local_scanner.go
=> Capitalize Mondoo Platform in help

policy/cnspec_policy_vtproto.pb.go, policy/policy.go
`CloneVT` is also something we will need, so I added it
=> ✨ generate vt clone functions for policies

README.md, content/mondoo-aws-security.mql.yaml, content/mondoo-azure-security.mql.yaml, content/mondoo-gcp-security.mql.yaml
I noticed this when writing opps for policy management
=> Remove more references to cnspec-policies

policy/bundle.go, policy/cnspec_policy.pb.go, policy/cnspec_policy.proto, policy/resolved_policy_builder.go, policy/resolver_v2_test.go, test/providers/scan_flags_test.go
Mostly code comments, but also an error message
=> Fix a few typos

.github/actions/spelling/patterns.txt, docs/development.md
Update formatting and golang version
=> Update to the setup instructions in the dev docs

content/mondoo-ms365-security.mql.yaml
Cleanup terms to match MS marketing dept
=> MS365 -> Microsoft 365

.github/actions/spelling/expect.txt, content/mondoo-linux-security.mql.yaml, content/mondoo-macos-security.mql.yaml
Expand our remediation steps here
=> Add more ansible remedations to the Linux policy

content/mondoo-macos-security.mql.yaml, content/mondoo-windows-security.mql.yaml
Make sure everything in macOS follows the new format and fix an incorrect GP step on Windows
=> Fill in missing remedations / improve steps

.github/actions/spelling/expect.txt, content/mondoo-linux-security.mql.yaml
Add more full remediations in the Linux policy
=> Fill in missing remedations / improve steps (#1742)

content/mondoo-aws-security.mql.yaml, content/mondoo-gcp-security.mql.yaml, content/mondoo-linux-security.mql.yaml, content/mondoo-linux-workstation-security.mql.yaml, content/vulnerabilities/mondoo-openssl-vulnerability.mql.yaml
- Fix formatting
- Expand remediations
=> Update remediation content

content/mondoo-linux-security.mql.yaml
Improve how this reads when you go to load the policy
=> Split network checks in Linux policy into a chapter

content/mondoo-linux-security.mql.yaml
=> Add more bash remediation steps to linux policy

content/mondoo-linux-security.mql.yaml
=> Add more bash remediation to the Linux policy

.github/actions/spelling/expect.txt, content/mondoo-linux-security.mql.yaml
- Minor formatting cleanup
- Add the immutable config check to more auditd remediations
- Add more bash remediations
=> Remediation updates for the Linux policy

content/mondoo-kubernetes-security.mql.yaml, content/mondoo-linux-security.mql.yaml, content/mondoo-linux-workstation-security.mql.yaml
Add some missing bash remediations
=> Add more bash remediations

go.mod, go.sum, policy/executor/internal/collector.go
Same as https://github.com/mondoohq/cnquery/pull/5845
=> ⚙️ Use cnquery's build flags to disable the max message size limitation.

.github/actions/spelling/expect.txt, content/mondoo-gcp-security.mql.yaml
This makes use of https://github.com/mondoohq/cnquery/pull/5743 to:
- rewrite the applicable checks
- adds new groups and checks
- Cloud KMS
- Cloud DNS
=> ⭐  Add more granularity to: Mondoo Google Cloud (GCP) Security v3.0.0

content/mondoo-linux-security.mql.yaml
This was in the wrong place so it didn't show up
=> Fix missing docs in Mondoo Linux policy

content/mondoo-linux-security.mql.yaml
Fix a failure loading the auditd rules
=> Fix a typo in Mondoo Linux policy bash auditd remediation

content/mondoo-linux-security.mql.yaml
Align the file name with the other file names
=> Improve the remediation for auditd sudo tracking

content/mondoo-gcp-security.mql.yaml
=> GCP policy: Swap MySQL for PostgreSQL in text

content/mondoo-github-security.mql.yaml
Add a few more terraform remediations
=> ⭐ Add additional automated remediation steps

.github/.goreleaser-edge.yml, .github/.goreleaser-unstable.yml
For edge and unstable builds, this will allow us to test.
=> 🐛 update goreleaser to v12

.github/workflows/bump-cnspec-in-deps.yaml, .github/workflows/cla.yaml, .github/workflows/cnquery-update.yml, .github/workflows/gh-release.yaml, .github/workflows/goreleaser-edge.yml, .github/workflows/goreleaser.yml, .github/workflows/license.yml, .github/workflows/link-check.yaml, .github/workflows/policies_lint.yaml, .github/workflows/pr-extended-linting.yml, .github/workflows/pr-test-lint.yml, .github/workflows/spell-check.yaml, .github/workflows/test-report.yml
Pin GitHub actions to their hashes.
https://github.com/mondoohq/cnquery/pull/5947
=> ✨ Pin GitHub actions to hashes
